/* TravelMate Pro VNext - 行程/城市/AI 完整交互 */
(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const KEY='lvban-trips-vnext';
const catalog={
福州:[['三坊七巷','福州市鼓楼区南后街'],['上下杭历史街区','福州市台江区下杭路'],['西禅寺','福州市鼓楼区工业路455号']],
平潭:[['猴研岛（68海里景区）','平潭县澳前镇东澳村'],['坛南湾田美澳沙滩','平潭县敖东镇坛南湾'],['仙人井','平潭县流水镇仙人井'],['北港文创村','平潭县流水镇北港村'],['镜沙黑沙滩','平潭县流水镇镜沙村'],['长江澳风车田','平潭县平原镇长江澳']],
泉州:[['开元寺','泉州市鲤城区西街176号'],['西街','泉州市鲤城区西街'],['洛伽寺','石狮市永宁镇黄金海岸宫屿岛'],['蟳埔村','泉州市丰泽区蟳埔社区'],['清净寺','泉州市鲤城区涂门街108号'],['关岳庙','泉州市鲤城区涂门街']],
厦门:[['鼓浪屿','厦门市思明区鼓浪屿'],['日光岩','厦门市思明区鼓浪屿晃岩路62号'],['菽庄花园','厦门市思明区鼓浪屿港后路3号'],['黄厝沙滩','厦门市思明区环岛南路黄厝海滨'],['南普陀寺','厦门市思明区思明南路515号'],['厦门园林植物园','厦门市思明区虎园路25号'],['钟鼓索道','厦门市思明区虎园路25-110号'],['沙坡尾艺术西区','厦门市思明区沙坡尾60号'],['集美学村','厦门市集美区银江路183号'],['十里长堤','厦门市集美区滨海西大道十里长堤']]
};
const foods={福州:[['老福洲（吉庇巷店）','福州市鼓楼区吉庇巷72-2号'],['没牙伯花生汤（老药洲店）','福州市台江区老药洲街182号']],平潭:[['十三妹咸米时店','平潭县西航路'],['毛记潮汕海鲜砂锅粥','平潭县翠园中路']],泉州:[['水门国仔面线糊','泉州市鲤城区水门巷21号'],['侯阿婆肉粽','泉州市鲤城区东街59号'],['好成财牛排馆','泉州市鲤城区涂门街221号']],厦门:[['八市阿杰五香','厦门市思明区开禾路111号'],['黄则和花生汤','厦门市思明区中山路22-24号'],['四里沙茶面','厦门市思明区湖滨四里14号'],['浮屿大同鸭肉粥','厦门市思明区厦禾路174号']]};
const hotels=[['9月28日','锦江都城酒店（福州三坊七巷东街口地铁站店）','福州市鼓楼区省府路9号'],['9月29日','维也纳酒店（福州平潭龙王头沙滩店）','平潭县海坛街道西航路190号'],['9月30日','丽怡酒店（平潭国际旅游岛店）','平潭县金井大道东段129-11号'],['备选','希岸酒店（福州平潭龙王头沙滩店）','平潭县万宝中路158号'],['10月1日','维也纳酒店（泉州古城浦西万达店）','泉州市丰泽区泉秀街768号'],['10月2-3日','希岸酒店（厦门火车站万象城店）','厦门市思明区厦禾路982号']];
function item(time,name,address,note=''){return{id:crypto.randomUUID?.()||Date.now()+Math.random(),time,name,address,note}}
const A=[['9月28日','福州',[item('24:00','抵达福州长乐国际机场','福州长乐国际机场','飞机'),item('00:40','前往锦江都城酒店','福州市鼓楼区省府路9号','网约车/出租车'),item('01:30','入住休息','福州市鼓楼区省府路9号','不安排景点')]],['9月29日','福州 → 平潭南线',[item('08:30','早餐','福州市鼓楼区省府路9号','锅边糊、海蛎饼'),item('09:15','三坊七巷','福州市鼓楼区南后街','南后街、衣锦坊、文儒坊'),item('11:15','老福洲（吉庇巷店）','福州市鼓楼区吉庇巷72-2号','午餐'),item('12:30','前往平潭','平潭县海坛街道西航路190号','包车/拼车或动车D9971'),item('14:00','维也纳酒店入住','平潭县海坛街道西航路190号','休整'),item('15:40','猴研岛（68海里景区）','平潭县澳前镇东澳村','南线核心'),item('17:10','坛南湾田美澳沙滩','平潭县敖东镇坛南湾','踏浪、日落'),item('19:30','平潭海鲜晚餐','平潭县西航路','晚餐'),item('21:00','龙王头海滨浴场','平潭县环岛东路龙王头海滨浴场','散步、可关注蓝眼泪')]],['9月30日','平潭北线',[item('06:50','龙王头沙滩日出','平潭县环岛东路龙王头海滨浴场','可选'),item('09:20','仙人井','平潭县流水镇仙人井',''),item('10:20','北港文创村','平潭县流水镇北港村','石头厝、咖啡'),item('11:00','北部湾生态廊道','平潭县北部生态廊道','环岛公路'),item('12:00','午餐','平潭县流水镇','海鲜面、海蛎煎'),item('14:00','镜沙黑沙滩','平潭县流水镇镜沙村','平潭小冰岛'),item('16:00','长江澳风车田','平潭县平原镇长江澳','踏浪、赶海、日落'),item('19:30','毛记潮汕海鲜砂锅粥','平潭县翠园中路','晚餐')]],['10月1日','平潭 → 泉州',[item('09:00','坛南湾晨间散步','平潭县敖东镇坛南湾','最后看海'),item('10:45','D6294 平潭 → 泉州','平潭站 → 泉州站','动车'),item('12:40','维也纳酒店入住','泉州市丰泽区泉秀街768号','休整'),item('14:30','开元寺','泉州市鲤城区西街176号','东西双塔'),item('16:00','西街逛吃','泉州市鲤城区西街','小吃'),item('18:30','泉州钟楼','泉州市鲤城区西街与中山路交叉口','拍照'),item('19:00','承天寺','泉州市鲤城区承天巷85号','夜游'),item('20:00','清净寺 + 关岳庙','泉州市鲤城区涂门街108号','步行连逛')]],['10月2日','泉州海边 → 厦门',[item('08:00','洛伽寺','石狮市永宁镇黄金海岸宫屿岛','海上佛国'),item('09:30','黄金海岸','石狮市永宁镇黄金海岸度假区','海边漫步'),item('11:30','泉州 → 厦门','泉州南站 → 厦门站','高铁'),item('13:30','希岸酒店入住','厦门市思明区厦禾路982号','休整'),item('16:00','黄厝沙滩','厦门市思明区环岛南路黄厝海滨','日落'),item('19:00','第八市场','厦门市思明区开禾路第八市场','逛吃'),item('20:30','中山路步行街','厦门市思明区中山路','骑楼夜景')]],['10月3日','鼓浪屿全天',[item('08:00','邮轮中心厦鼓码头','厦门市思明区东港路2号','地铁2号线/打车'),item('08:30','三丘田码头登岛','厦门市思明区鼓浪屿三丘田码头','轮渡'),item('09:00','最美转角 + 风琴博物馆','厦门市思明区鼓新路43号','步行'),item('10:00','日光岩','厦门市思明区鼓浪屿晃岩路62号','登顶'),item('11:30','龙头路','厦门市思明区鼓浪屿龙头路','午餐逛店'),item('13:30','菽庄花园 + 钢琴博物馆','厦门市思明区鼓浪屿港后路3号','精华游'),item('15:00','港仔后沙滩','厦门市思明区鼓浪屿港仔后','散步'),item('17:30','三丘田码头返程','厦门市思明区鼓浪屿三丘田码头','回市区'),item('19:00','万象城晚餐','厦门市思明区厦禾路982号','晚餐')]],['10月4日','厦门压轴半日 → 返程',[item('07:30','南普陀寺','厦门市思明区思明南路515号','祈福'),item('09:20','厦门园林植物园','厦门市思明区虎园路25号','雨林世界'),item('11:30','午餐','厦门市思明区虎园路周边','闽南家常菜'),item('14:20','钟鼓索道','厦门市思明区虎园路25-110号','空中俯瞰厦门'),item('16:00','返回酒店取行李','厦门市思明区厦禾路982号','退房'),item('17:00','前往机场/车站','厦门高崎机场 / 厦门站 / 厦门北站','返程杭州')]];
const B=[A[0],A[1],A[2],['10月1日','平潭 → 厦门',[item('09:00','坛南湾晨间散步 / 将军山','平潭县敖东镇坛南湾','南线收尾'),item('11:54','C5192 平潭 → 厦门','平潭站 → 厦门站','动车直达'),item('14:45','希岸酒店入住','厦门市思明区厦禾路982号','休整'),item('16:30','沙坡尾艺术西区','厦门市思明区沙坡尾60号','逛拍'),item('18:00','演武大桥观景平台','厦门市思明区演武大桥旁','日落'),item('18:40','第八市场','厦门市思明区开禾路第八市场','逛吃'),item('20:30','中山路','厦门市思明区中山路','骑楼夜景')]],A[5],['10月3日','集美学村 + 十里长堤',[item('09:00','四里沙茶面','厦门市思明区湖滨四里14号','早餐'),item('09:30','集美学村','厦门市集美区银江路183号','地铁1号线'),item('12:00','石鼓路美食街','厦门市集美区石鼓路','午餐'),item('13:30','鳌园 + 陈嘉庚纪念馆','厦门市集美区鳌园路24号','免费，需预约'),item('15:30','南堤公园','厦门市集美区南堤','看海'),item('16:30','十里长堤','厦门市集美区滨海西大道十里长堤','日落'),item('19:00','返回市区酒店','厦门市思明区厦禾路982号','地铁1号线')]],A[6]];
let trips=JSON.parse(localStorage.getItem(KEY)||'[]');let selectedTrip=null,selectedCity=null,selectedDay=0,selectedRoute=0;
function save(){localStorage.setItem(KEY,JSON.stringify(trips))} function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1400)}
function go(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.bottom button').forEach(b=>b.classList.toggle('on',b.dataset.page===id));if(id==='home')renderHome();if(id==='trips')renderTrips();if(id==='spots')renderCatalog('spot');if(id==='food')renderCatalog('food');if(id==='hotels')renderHotels();if(id==='ai'){}scrollTo(0,0)}
function nav(n,a){window.open('https://uri.amap.com/search?keyword='+encodeURIComponent(n+' '+a),'_blank')}function copy(t){navigator.clipboard?.writeText(t);toast('已复制')}
function renderHome(){let next=trips.filter(t=>t.start).sort((a,b)=>new Date(a.start)-new Date(b.start)).find(t=>new Date(t.start)>=new Date(new Date().toDateString()));let d=next?Math.ceil((new Date(next.start)-new Date(new Date().toDateString()))/86400000):null;$('#countdown').innerHTML=next?`<b>${d===0?'今天出发':`还有 ${d} 天`}</b><span>${esc(next.name)} · ${esc(next.cities.join(' / '))}</span>`:'<b>暂无即将出发的行程</b><span>创建行程后自动关联最近一次出发日期</span>'}
function renderTrips(){let el=$('#tripList');el.innerHTML=`<div class="trip-head"><div><h2>我的行程</h2><p>你的旅行计划都在这里</p></div><button class="newTripBtn" onclick="newTrip()">＋ 新建行程</button></div>`+(trips.length?`<div class="tripgrid">${trips.map((t,i)=>`<article class="trip-card"><button class="more" onclick="tripMenu(event,${i})">•••</button><div class="trip-cover">${esc(t.cities.slice(0,3).join(' · '))}</div><h3>${esc(t.name)}</h3><div class="trip-meta">${t.start} — ${t.end}</div><div class="trip-meta">${t.cities.length} 个目的地 · ${t.days.length} 天</div><button class="openTrip" onclick="openTrip(${i})">打开行程</button></article>`).join('')}</div>`:'<div class="empty card"><div class="big">🧳</div><h3>还没有行程</h3><p>创建你的第一个旅行计划，选择城市后开始安排每天的行程。</p><button class="newTripBtn" onclick="newTrip()">＋ 新建行程</button></div>') ;if(selectedTrip!==null)renderTripDetail()}
function tripMenu(e,i){e.stopPropagation();modal('行程操作',`<div class="menuList"><button onclick="editTrip(${i})">✏️ 编辑行程</button><button onclick="duplicateTrip(${i})">📋 复制行程</button><button onclick="toast('已收藏');closeModal()">☆ 收藏</button><button class="dangerText" onclick="deleteTrip(${i})">🗑 删除行程</button></div>`)}
function openTrip(i){selectedTrip=i;selectedDay=0;selectedRoute=0;renderTrips()}function duplicateTrip(i){let t=JSON.parse(JSON.stringify(trips[i]));t.id=Date.now();t.name+='（副本）';trips.push(t);save();closeModal();renderTrips();toast('已复制')}
function deleteTrip(i){if(confirm(`确定删除“${trips[i].name}”？`)){trips.splice(i,1);selectedTrip=null;save();closeModal();renderTrips();renderHome();toast('行程已删除')}}
function currentDays(){if(selectedTrip!==null)return trips[selectedTrip].days;return selectedRoute===0?A.map(x=>({date:x[0],title:x[1],city:guessCity(x[1]),items:x[2]})):B.map(x=>({date:x[0],title:x[1],city:guessCity(x[1]),items:x[2]}))}
function guessCity(s){for(const c of Object.keys(catalog))if(String(s).includes(c))return c;return s.includes('厦门')?'厦门':s.includes('平潭')?'平潭':s.includes('泉州')?'泉州':'福州'}
function renderTripDetail(){let t=trips[selectedTrip];let days=t.days;let d=days[selectedDay]||days[0];$('#tripDetail').innerHTML=`<div class="detail panel"><div class="detail-top"><div><button class="back" onclick="selectedTrip=null;renderTrips()">‹ 我的行程</button><h2>${esc(t.name)}</h2><p>${esc(t.cities.join(' · '))} · ${t.start} — ${t.end}</p></div><button class="dangerBtn" onclick="deleteTrip(${selectedTrip})">删除总行程</button></div>${t.routes?.length>1?`<div class="routeTabs">${t.routes.map((r,i)=>`<button class="route ${i===selectedRoute?'on':''}" onclick="selectedRoute=${i};selectedDay=0;renderTripDetail()">${esc(r.name)}</button>`).join('')}</div>`:''}<div class="cityTabs">${t.cities.map(c=>`<button class="cityTab ${c===selectedCity?'on':''}" onclick="selectCity('${esc(c)}')">${esc(c)}</button>`).join('')}</div><div class="dateTabs">${days.map((x,i)=>`<button class="dateTab ${i===selectedDay?'on':''}" onclick="selectedDay=${i};renderTripDetail()"><b>${esc(x.date)}</b><small>${esc(x.city||'')}</small></button>`).join('')}</div><div class="dayHeader"><div><span>DAY ${selectedDay+1}</span><h3>${esc(d.title||d.city)}</h3></div><div><button class="btn" onclick="addDay()">＋ 增加一天</button><button class="dangerMini" onclick="deleteDay()">删除当天</button></div></div><div class="timeline">${d.items.length?d.items.map((x,i)=>eventHTML(x,i)).join(''):'<div class="empty">今天还没有安排，点击“添加日程”开始。</div>'}</div><button class="addEventBtn" onclick="addEvent()">＋ 添加日程</button></div>`}
function selectCity(c){selectedCity=c;let t=trips[selectedTrip];let idx=t.days.findIndex(d=>d.city===c);if(idx>=0)selectedDay=idx;renderTripDetail()}
function eventHTML(x,i){return `<article class="event"><div class="eventTime">${esc(x.time)}</div><div class="eventBody"><h3>${esc(x.name)}</h3><div class="address">📍 ${esc(x.address||'未填写地址')}</div>${x.note?`<p>${esc(x.note)}</p>`:''}<div class="eventActions"><button onclick="copy('${String(x.address||'').replace(/'/g,"\\'")}')">复制地址</button><button onclick="nav('${String(x.name).replace(/'/g,"\\'")}','${String(x.address||'').replace(/'/g,"\\'")}')">导航</button><button onclick="editEvent(${i})">编辑</button><button class="dangerText" onclick="deleteEvent(${i})">删除</button></div></div></article>`}
function addEvent(){let t=trips[selectedTrip],d=t.days[selectedDay];modal('添加日程',`<div class="form"><label>时间</label><input id="fTime" type="time" value="09:00"><label>安排什么</label><input id="fName" placeholder="搜索景点/美食，或自己填写" oninput="recommend(this.value)"><div id="recommend" class="recommend"></div><label>地址</label><input id="fAddr" placeholder="选择推荐后自动填入"><label>备注</label><textarea id="fNote"></textarea><button class="primary wide" onclick="saveEvent()">加入当天行程</button></div>`);recommend('')}
function recommend(q){let d=trips[selectedTrip].days[selectedDay],city=d.city||trips[selectedTrip].cities[0];let all=[...(catalog[city]||[]),...(foods[city]||[])].filter(x=>!q||x[0].includes(q));$('#recommend').innerHTML=all.slice(0,8).map(x=>`<button type="button" onclick="pickRec('${esc(x[0])}','${esc(x[1])}')"><b>${esc(x[0])}</b><small>${esc(x[1])}</small></button>`).join('')||'<span>没有匹配项，可以手动填写。</span>'}
function pickRec(n,a){$('#fName').value=n;$('#fAddr').value=a;toast('已填入日程')}function saveEvent(){let d=trips[selectedTrip].days[selectedDay];if(!$('#fName').value.trim())return toast('请填写安排内容');d.items.push(item($('#fTime').value,$('#fName').value,$('#fAddr').value,$('#fNote').value));d.items.sort((a,b)=>a.time.localeCompare(b.time));save();closeModal();renderTripDetail();toast('已加入当天行程')}
function editEvent(i){let x=trips[selectedTrip].days[selectedDay].items[i];modal('编辑日程',`<div class="form"><label>时间</label><input id="fTime" type="time" value="${esc(x.time)}"><label>名称</label><input id="fName" value="${esc(x.name)}"><label>地址</label><input id="fAddr" value="${esc(x.address)}"><label>备注</label><textarea id="fNote">${esc(x.note||'')}</textarea><button class="primary wide" onclick="let d=trips[selectedTrip].days[selectedDay];d.items[${i}]=Object.assign({},d.items[${i}],{time:$('#fTime').value,name:$('#fName').value,address:$('#fAddr').value,note:$('#fNote').value});save();closeModal();renderTripDetail()">保存修改</button></div>`)}
function deleteEvent(i){if(confirm('确定删除这条详细日程？')){trips[selectedTrip].days[selectedDay].items.splice(i,1);save();renderTripDetail();toast('日程已删除')}}
function addDay(){let t=trips[selectedTrip];let last=t.days[t.days.length-1];let dt=new Date(last.rawDate||t.start);dt.setDate(dt.getDate()+1);t.days.push({date:`${dt.getMonth()+1}月${dt.getDate()}日`,rawDate:dt.toISOString().slice(0,10),city:t.cities[0],title:t.cities[0],items:[]});save();selectedDay=t.days.length-1;renderTripDetail()}
function deleteDay(){if(trips[selectedTrip].days.length<=1)return toast('至少保留一天');if(confirm('确定删除当天及当天全部日程？')){trips[selectedTrip].days.splice(selectedDay,1);selectedDay=Math.max(0,selectedDay-1);save();renderTripDetail();toast('当天已删除')}}
function newTrip(){modal('新建行程',`<div class="form"><label>行程名称</label><input id="tName" placeholder="例如：十一福建游"><label>开始日期</label><input id="tStart" type="date"><label>结束日期</label><input id="tEnd" type="date"><label>目的地</label><button class="selectBox" onclick="cityPicker()" id="cityBox">选择城市（支持多选）</button><div id="pickedCities" class="picked"></div><label class="check"><input id="backup" type="checkbox" onchange="$('#backupHint').textContent=this.checked?'已开启备选路线：创建后可切换多个方案':'关闭后只生成一套行程'"> 是否有备选路线</label><div id="backupHint" class="hint">关闭后只生成一套行程</div><label>创建方式</label><div class="createModes"><button class="mode on" id="selfMode" onclick="setMode('self')">📝 我自己安排</button><button class="mode" id="aiMode" onclick="setMode('ai')">✨ AI 帮我规划</button></div><button class="primary wide" onclick="createTrip()">创建行程</button></div>`);window.newCities=[];window.createMode='self'}
function cityPicker(){let selected=new Set(window.newCities||[]);modal('选择目的地',`<div class="citySearch"><input id="citySearch" placeholder="搜索城市，例如：厦门、杭州" oninput="renderCityPicker(this.value)"></div><div id="cityPickerList"></div><button class="primary wide" onclick="applyCities()">确定（${selected.size}）</button>`);window.citySet=selected;renderCityPicker('')}
function renderCityPicker(q){let arr=window.LVBAN_CITY_LIST||[];q=(q||'').trim();let html='';if(q){arr=arr.filter(x=>x.city.includes(q)||x.province.includes(q));html=`<div class="cityResults">${arr.slice(0,60).map(x=>`<button class="cityOption ${window.citySet.has(x.city)?'on':''}" onclick="toggleCity('${esc(x.city)}')"><span>${esc(x.city)}</span><small>${esc(x.province)}</small>${window.citySet.has(x.city)?'✓':''}</button>`).join('')||'<div class="empty">没有找到城市</div>'}</div>`}else{for(const p of Object.keys(window.LVBAN_CITIES||{})){html+=`<div class="province"><b>${p}</b><div>${window.LVBAN_CITIES[p].slice(0,12).map(c=>`<button class="cityChip ${window.citySet.has(c)?'on':''}" onclick="toggleCity('${esc(c)}')">${esc(c)}</button>`).join('')}</div></div>`}}$('#cityPickerList').innerHTML=html}
function toggleCity(c){window.citySet.has(c)?window.citySet.delete(c):window.citySet.add(c);renderCityPicker($('#citySearch')?.value||'')}
function applyCities(){window.newCities=[...window.citySet];closeModal();$('#pickedCities').innerHTML=window.newCities.map(c=>`<span>${esc(c)} ×</span>`).join('')||'<span class="placeholder">还没有选择城市</span>';$('#cityBox').textContent=window.newCities.length?`已选择 ${window.newCities.length} 个城市`:'选择城市（支持多选）';}
function setMode(m){window.createMode=m;$('#selfMode').classList.toggle('on',m==='self');$('#aiMode').classList.toggle('on',m==='ai')}
function createTrip(){let name=$('#tName').value.trim(),start=$('#tStart').value,end=$('#tEnd').value,cities=window.newCities||[];if(!name||!start||!end||!cities.length)return toast('请完整填写名称、日期和目的地');if(new Date(end)<new Date(start))return toast('结束日期不能早于开始日期');let total=Math.round((new Date(end)-new Date(start))/86400000)+1;let allocations=cities.map((c,i)=>({city:c,days:i===cities.length-1?Math.max(1,total-cities.slice(0,-1).reduce((s,x)=>s+(x.days||1),0)):1}));if(cities.length>1)allocations=Array.from({length:cities.length},(_,i)=>({city:cities[i],days:Math.floor(total/cities.length)+(i<total%cities.length?1:0)}));let days=[],cur=new Date(start);allocations.forEach(a=>{for(let j=0;j<a.days;j++){days.push({date:`${cur.getMonth()+1}月${cur.getDate()}日`,rawDate:cur.toISOString().slice(0,10),city:a.city,title:a.city,items:[]});cur.setDate(cur.getDate()+1)}});let t={id:Date.now(),name,start,end,cities,days,routes:$('#backup').checked?[{name:'方案 A',days:JSON.parse(JSON.stringify(days))},{name:'方案 B',days:JSON.parse(JSON.stringify(days))}]:[{name:'我的行程',days}],mode:window.createMode};trips.push(t);save();closeModal();selectedTrip=trips.length-1;selectedDay=0;go('trips');renderHome();toast('行程创建成功')}
function editTrip(i){let t=trips[i];modal('编辑行程',`<div class="form"><label>名称</label><input id="eName" value="${esc(t.name)}"><label>开始日期</label><input id="eStart" type="date" value="${t.start}"><label>结束日期</label><input id="eEnd" type="date" value="${t.end}"><button class="primary wide" onclick="trips[${i}].name=$('#eName').value;trips[${i}].start=$('#eStart').value;trips[${i}].end=$('#eEnd').value;save();closeModal();renderTrips();renderHome()">保存</button></div>`)}
function renderCatalog(type){let source=type==='spot'?catalog:foods;let html=`<div class="title"><div><h2>${type==='spot'?'景点':'美食'}</h2><p>按城市浏览，支持复制地址和导航</p></div></div><div class="chips">${Object.keys(source).map(c=>`<button class="chip" onclick="showCatalog('${type}','${esc(c)}')">${esc(c)}</button>`).join('')}</div><div id="catalogResults"><div class="empty card">请选择城市</div></div>`;$('#'+(type==='spot'?'spots':'food')).innerHTML=html}
function showCatalog(type,city){let source=type==='spot'?catalog:foods;$('#catalogResults').innerHTML=(source[city]||[]).map(x=>`<article class="data card"><span class="city">${esc(city)}</span><h3>${esc(x[0])}</h3><div class="address">📍 ${esc(x[1])}</div><div class="eventActions"><button onclick="copy('${x[1].replace(/'/g,"\\'")}')">复制地址</button><button onclick="nav('${x[0].replace(/'/g,"\\'")}','${x[1].replace(/'/g,"\\'")}')">导航</button>${selectedTrip!==null?`<button onclick="addCatalog('${x[0].replace(/'/g,"\\'")}','${x[1].replace(/'/g,"\\'")}')">加入当前日程</button>`:''}</div></article>`).join('')||'<div class="empty">暂无数据</div>'}
function addCatalog(n,a){if(selectedTrip===null)return toast('请先打开一个行程');trips[selectedTrip].days[selectedDay].items.push(item('—',n,a,'从景点/美食库加入'));save();go('trips');renderTripDetail();toast('已加入当前日程')}
function renderHotels(){$('#hotels').innerHTML=`<div class="title"><h2>酒店</h2></div>`+hotels.map(x=>`<article class="data card"><span class="city">${x[0]}</span><h3>${x[1]}</h3><div class="address">📍 ${x[2]}</div><div class="eventActions"><button onclick="copy('${x[2].replace(/'/g,"\\'")}')">复制地址</button><button onclick="nav('${x[1].replace(/'/g,"\\'")}','${x[2].replace(/'/g,"\\'")}')">导航</button></div></article>`).join('')}
function askAI(){let text=$('#aiInput').value.trim();if(!text)return;$('#aiInput').value='';let box=$('#messages');box.insertAdjacentHTML('beforeend',`<div class="msg user">${esc(text)}</div>`);let p=document.createElement('div');p.className='msg ai';p.textContent='正在思考…';box.appendChild(p);let context=selectedTrip!==null?trips[selectedTrip]:null;fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:[...$$('#messages .msg')].slice(-12).map(m=>({role:m.classList.contains('user')?'user':'assistant',content:m.textContent})),tripContext:context})}).then(r=>r.json()).then(j=>p.textContent=j.reply||j.error||'暂时没有得到回复').catch(()=>p.textContent='AI 暂时无法连接，请检查 Functions /api/ai。')}
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(trips,null,2)],{type:'application/json'}));a.download='旅伴行程备份.json';a.click()}
function modal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.add('show')}function closeModal(){$('#modal').classList.remove('show')}
window.newTrip=newTrip;window.go=go;window.tripMenu=tripMenu;window.openTrip=openTrip;window.deleteTrip=deleteTrip;window.editTrip=editTrip;window.duplicateTrip=duplicateTrip;window.addEvent=addEvent;window.deleteEvent=deleteEvent;window.editEvent=editEvent;window.addDay=addDay;window.deleteDay=deleteDay;window.cityPicker=cityPicker;window.renderCityPicker=renderCityPicker;window.toggleCity=toggleCity;window.applyCities=applyCities;window.setMode=setMode;window.createTrip=createTrip;window.pickRec=pickRec;window.recommend=recommend;window.saveEvent=saveEvent;window.nav=nav;window.copy=copy;window.closeModal=closeModal;window.askAI=askAI;window.showCatalog=showCatalog;window.addCatalog=addCatalog;window.exportData=exportData;
window.addEventListener('load',()=>{renderHome();renderTrips();renderCatalog('spot');renderCatalog('food');renderHotels();});
})();
