/* TravelMate - stable interactive UI */
(()=>{
'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const toast=m=>{const t=$('#toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}}; window.toast=toast;
function store(){return window.LvbanStore?window.LvbanStore.get():{trips:window.db?.trips||[]}}
function save(){if(window.save)window.save();else if(window.LvbanStore)window.LvbanStore.patch(s=>s.trips=window.db.trips);}
function trip(){return window.currentTrip?.()||window.db?.trips?.find(x=>x.id===window.activeTrip)}
function plan(){return window.currentPlan?.()||trip()?.plans?.find(x=>x.id===window.activePlan)||trip()?.plans?.[0]}
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));document.querySelectorAll('.bottom button').forEach(x=>x.classList.toggle('on',x.dataset.page===page));if(page==='trips')renderTrips();if(page==='spots')renderCatalog('spots');if(page==='food')renderCatalog('food');if(page==='hotels')renderHotels();if(page==='traffic')renderTraffic();if(page==='home')renderHome();}
window.go=go;
function renderHome(){const c=$('#countdown');const trips=window.db?.trips||[];const today=new Date();today.setHours(0,0,0,0);const upcoming=trips.filter(t=>t.start&&new Date(t.start+'T00:00:00')>=today).sort((a,b)=>a.start.localeCompare(b.start))[0];if(c){if(upcoming){const d=Math.ceil((new Date(upcoming.start+'T00:00:00')-today)/86400000);c.innerHTML=`<div><span>最近一次旅行</span><b>${d===0?'今天':`还有 ${d} 天`}</b></div><strong>${esc(upcoming.name)}</strong><small>${esc(upcoming.start)} · ${esc(upcoming.city||'')}</small>`}else c.innerHTML='<span>还没有未来行程</span><button class="newTripBtn" onclick="newTrip()">创建行程</button>'}}
function renderTrips(){const root=$('#tripList'),detail=$('#tripDetail');if(!root||!detail)return;detail.innerHTML='';const trips=window.db?.trips||[];root.innerHTML=`<div class="trip-head"><div><h2>我的行程</h2><p>管理你的旅行计划</p></div><button class="newTripBtn" onclick="newTrip()">＋ 新建行程</button></div>`;if(!trips.length){root.innerHTML+='<div class="empty"><div class="big">🗓️</div><p>还没有行程，创建一个开始吧</p><button class="newTripBtn" onclick="newTrip()">创建行程</button></div>';return}const grid=document.createElement('div');grid.className='tripgrid';trips.forEach(t=>{const card=document.createElement('div');card.className='trip-card';card.innerHTML=`<button class="more" onclick="tripMenu('${t.id}')">•••</button><div class="trip-cover">${esc(t.city||'旅行')}</div><h3>${esc(t.name)}</h3><div class="trip-meta">${esc(t.start||'')} → ${esc(t.end||'')}</div><div class="trip-meta">${esc(t.city||'未设置目的地')}</div><button class="openTrip" onclick="openTrip('${t.id}')">查看行程</button>`;grid.appendChild(card)});root.appendChild(grid)}
window.openTrip=id=>{window.selectTrip?.(id);renderTripDetail()};
function renderTripDetail(){const t=trip(),root=$('#tripList'),detail=$('#tripDetail');if(!t||!root||!detail)return;root.innerHTML='';detail.innerHTML='';const p=plan();detail.innerHTML=`<div class="detail-top"><div><button class="back" onclick="go('trips')">‹ 返回我的行程</button><h2>${esc(t.name)}</h2><p>${esc(t.city||'')}</p></div><button class="more" style="position:static" onclick="tripMenu('${t.id}')">•••</button></div>${t.plans?.length>1?`<div class="routeTabs">${t.plans.map(x=>`<button class="route ${x.id===p.id?'on':''}" onclick="switchRoute('${x.id}')">${esc(x.name)}</button>`).join('')}</div>`:''}<div class="dateTabs">${(p?.days||[]).map((d,i)=>`<button class="dateTab ${i===window.activeDay?'on':''}" onclick="selectDay(${i})"><b>${esc((d.date||'').slice(5))}</b><small>${esc(d.title||'待安排')}</small></button>`).join('')}</div><div class="dayHeader"><div><h3>${esc(p?.days?.[window.activeDay]?.title||'当天行程')}</h3><p>${esc(p?.days?.[window.activeDay]?.date||'')}</p></div><div><button class="btn" onclick="deleteDay()">删除当天</button> <button class="btn" onclick="addDay()">＋ 添加一天</button></div></div><div class="timeline">${(p?.days?.[window.activeDay]?.items||[]).map((x,i)=>eventHTML(x,i)).join('')}</div><button class="addEventBtn" onclick="openDayEditor()">＋ 添加日程</button>`}
window.renderTripDetail=renderTripDetail;function eventHTML(x,i){return `<div class="event"><div class="eventTime">${esc(x.time||'')}</div><div class="eventBody"><h3>${esc(x.name)}</h3><div class="address">📍 ${esc(x.address||'暂无地址')}</div>${x.note?`<p>${esc(x.note)}</p>`:''}<div class="eventActions"><button onclick="openItemEditor(${i})">编辑</button><button onclick="deleteItem(${i})" class="dangerText">删除</button><button onclick="copyText('${encodeURIComponent(x.address||'')}')">复制地址</button><button onclick="navigateTo('${encodeURIComponent(x.address||x.name)}')">导航</button></div></div></div>`}
window.selectDay=i=>{window.activeDay=i;renderTripDetail()};window.switchRoute=id=>{window.activePlan=id;window.activeDay=0;renderTripDetail()};
window.deleteDay=()=>{const p=plan();if(!p?.days?.length)return;if(!confirm('删除当天及当天所有日程？'))return;p.days.splice(window.activeDay,1);if(!p.days.length)p.days.push({id:uid(),label:'DAY 1',date:trip().start,title:'待安排',items:[]});window.activeDay=Math.max(0,Math.min(window.activeDay,p.days.length-1));save();renderTripDetail()};
window.addDay=()=>{const p=plan();const last=p.days[p.days.length-1];const d=new Date((last?.date||trip().end)+'T00:00:00');d.setDate(d.getDate()+1);p.days.push({id:uid(),label:'DAY '+(p.days.length+1),date:d.toISOString().slice(0,10),title:'待安排',items:[]});window.activeDay=p.days.length-1;save();renderTripDetail()};
window.tripMenu=id=>{const t=window.db.trips.find(x=>x.id===id);if(!t)return;openModal('行程操作',`<div class="menuList"><button onclick="editTrip('${id}')">编辑行程</button><button onclick="duplicateTrip('${id}')">复制行程</button><button onclick="favoriteTrip('${id}')">收藏行程</button><button class="dangerText" onclick="deleteTrip('${id}')">删除行程</button></div>`) };
window.deleteTrip=id=>{if(!confirm('确定删除整个行程吗？删除后无法恢复。'))return;window.db.trips=window.db.trips.filter(x=>x.id!==id);save();closeModal();window.activeTrip=window.db.trips[0]?.id||null;renderTrips();toast('行程已删除')};window.duplicateTrip=id=>{const t=JSON.parse(JSON.stringify(window.db.trips.find(x=>x.id===id)));t.id=uid();t.name+='（副本）';window.db.trips.push(t);save();closeModal();renderTrips();toast('已复制')};window.favoriteTrip=id=>{closeModal();toast('已收藏')};window.editTrip=id=>{const t=window.db.trips.find(x=>x.id===id);closeModal();openModal('编辑行程',`<div class="form"><label>行程名称</label><input id="etName" value="${esc(t.name)}"><label>目的地</label><input id="etCity" value="${esc(t.city||'')}"><button class="btn primary" onclick="saveTripEdit('${id}')">保存</button></div>`) };window.saveTripEdit=id=>{const t=window.db.trips.find(x=>x.id===id);t.name=$('#etName').value.trim()||t.name;t.city=$('#etCity').value.trim()||t.city;save();closeModal();renderTrips()};
window.newTrip=()=>openModal('新建行程',`<div class="form"><label>行程名称</label><input id="ntName" placeholder="例如：十一福建游"><label>目的地（支持多选）</label><input id="ntCitySearch" placeholder="搜索城市，例如：厦门、福州"><div id="cityPicker" class="cityResults"></div><div id="pickedCities" class="picked"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><div><label>开始日期</label><input id="ntStart" type="date"></div><div><label>结束日期</label><input id="ntEnd" type="date"></div></div><label class="check"><input id="ntAlternate" type="checkbox"> 是否有备选路线（勾选后才生成 A / B）</label><div class="createModes"><button class="mode on" id="manualMode" onclick="chooseMode('manual')">我自己安排</button><button class="mode" id="aiMode" onclick="chooseMode('ai')">AI 帮我规划</button></div><button class="btn primary wide" onclick="createTrip()">创建行程</button></div>`);initCityPicker()};
function uid(){return 'lv-'+Date.now()+Math.random().toString(36).slice(2,7)}function openModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.add('show')}function closeModal(){$('#modal')?.classList.remove('show')}window.closeModal=closeModal;
let chosenCities=[],createMode='manual';function chooseMode(m){createMode=m;$('#manualMode')?.classList.toggle('on',m==='manual');$('#aiMode')?.classList.toggle('on',m==='ai')};window.chooseMode=chooseMode;
function initCityPicker(){const data=window.CITY_DATA||window.cities||window.LVBAN_CITIES||[];const arr=Array.isArray(data)?data:(typeof data==='object'?Object.values(data).flat().map(x=>typeof x==='string'?x:(x.name||x.city)):[]);const cities=[...new Set(arr.filter(Boolean))];const fallback=['北京','上海','广州','深圳','杭州','成都','重庆','西安','福州','平潭','泉州','厦门','南京','苏州','武汉','长沙','青岛','大连','三亚','桂林'];const list=cities.length?cities:fallback;const render=q=>{$('#cityPicker').innerHTML=list.filter(c=>!q||c.includes(q)).slice(0,80).map(c=>`<button class="cityOption ${chosenCities.includes(c)?'on':''}" onclick="toggleCity('${esc(c)}')"><span>${esc(c)}</span><small>${chosenCities.includes(c)?'已选择':'选择'}</small></button>`).join('')||'<div class="empty">没有找到城市</div>'};$('#ntCitySearch').oninput=e=>render(e.target.value.trim());render('');window.toggleCity=c=>{if(chosenCities.includes(c))chosenCities=chosenCities.filter(x=>x!==c);else chosenCities.push(c);$('#pickedCities').innerHTML=chosenCities.map(x=>`<span>${esc(x)} ×</span>`).join('');render($('#ntCitySearch').value.trim())};}
window.createTrip=()=>{const name=$('#ntName').value.trim(),start=$('#ntStart').value,end=$('#ntEnd').value,alternate=$('#ntAlternate').checked;if(!name||!start||!end)return toast('请填写行程名称和日期');if(end<start)return toast('结束日期不能早于开始日期');if(!chosenCities.length)return toast('请选择至少一个目的地');const days=[];let d=new Date(start+'T00:00:00'),last=new Date(end+'T00:00:00');while(d<=last){days.push({id:uid(),label:'DAY '+(days.length+1),date:d.toISOString().slice(0,10),title:chosenCities.length>1?chosenCities[Math.min(days.length,chosenCities.length-1)]+' · 待安排':'待安排',items:[]});d.setDate(d.getDate()+1)}const clone=()=>JSON.parse(JSON.stringify(days)).map(x=>({...x,id:uid(),items:[]}));const t={id:uid(),name,city:chosenCities.join(' · '),start,end,people:1,hasAlternateRoutes:alternate,plans:[{id:'A',name:'方案 A',days:clone()}]};if(alternate)t.plans.push({id:'B',name:'方案 B',days:clone()});window.db.trips.push(t);window.activeTrip=t.id;window.activePlan='A';window.activeDay=0;save();chosenCities=[];closeModal();renderTrips();toast(alternate?'创建成功：已生成 A / B':'创建成功：单一路线');if(createMode==='ai')setTimeout(()=>go('ai'),200)};
window.copyText=s=>{const x=decodeURIComponent(s||'');navigator.clipboard?.writeText(x);toast('已复制地址')};window.navigateTo=s=>{const x=decodeURIComponent(s||'');window.open('https://www.amap.com/search?query='+encodeURIComponent(x),'_blank');};
window.openDayEditor=()=>{openModal('添加日程',`<div class="form"><label>时间</label><input id="diTime" type="time" value="09:00"><label>安排什么？</label><input id="diName" placeholder="例如：南普陀寺"><label>地址</label><input id="diAddr" placeholder="输入地址"><label>备注</label><textarea id="diNote"></textarea><button class="btn primary" onclick="saveDayItem()">加入当天行程</button></div>`) };
window.saveDayItem=()=>{const d=plan()?.days?.[window.activeDay];const n=$('#diName').value.trim();if(!d||!n)return toast('请填写日程名称');d.items.push({id:uid(),time:$('#diTime').value||'09:00',name:n,address:$('#diAddr').value.trim(),note:$('#diNote').value.trim()});d.items.sort((a,b)=>a.time.localeCompare(b.time));save();closeModal();renderTripDetail();};window.openItemEditor=i=>{const x=plan()?.days?.[window.activeDay]?.items?.[i];if(!x)return;openModal('编辑日程',`<div class="form"><label>时间</label><input id="eiTime" type="time" value="${esc(x.time)}"><label>名称</label><input id="eiName" value="${esc(x.name)}"><label>地址</label><input id="eiAddr" value="${esc(x.address)}"><label>备注</label><textarea id="eiNote">${esc(x.note||'')}</textarea><button class="btn primary" onclick="saveItemEdit(${i})">保存修改</button></div>`)};window.saveItemEdit=i=>{const x=plan().days[window.activeDay].items[i];x.time=$('#eiTime').value;x.name=$('#eiName').value.trim();x.address=$('#eiAddr').value.trim();x.note=$('#eiNote').value.trim();save();closeModal();renderTripDetail()};window.deleteItem=i=>{const d=plan().days[window.activeDay];if(confirm('删除这条日程？')){d.items.splice(i,1);save();renderTripDetail()}};
function renderCatalog(type){const root=$('#'+type);if(!root)return;const data=window.LVBAN_DATA||{};const arr=type==='spots'?(data.spots||[]):(data.foods||[]);root.innerHTML=`<div class="title"><h2>${type==='spots'?'景点':'美食'}</h2></div><div class="chips">${[...new Set(arr.map(x=>x.city).filter(Boolean))].map(c=>`<button class="chip" onclick="filterCatalog('${type}','${esc(c)}')">${esc(c)}</button>`).join('')}</div><div id="${type}List" class="tripgrid">${arr.map(x=>`<div class="card"><div class="city">${esc(x.city||'')}</div><h3>${esc(x.name)}</h3><p>📍 ${esc(x.address||'')}</p><button class="btn" onclick="navigateTo('${encodeURIComponent(x.address||x.name)}')">导航</button></div>`).join('')}</div>`}window.filterCatalog=(type,city)=>{const data=window.LVBAN_DATA||{};const arr=(type==='spots'?(data.spots||[]):(data.foods||[])).filter(x=>x.city===city);$('#'+type+'List').innerHTML=arr.map(x=>`<div class="card"><div class="city">${esc(x.city||'')}</div><h3>${esc(x.name)}</h3><p>📍 ${esc(x.address||'')}</p><button class="btn" onclick="navigateTo('${encodeURIComponent(x.address||x.name)}')">导航</button></div>`).join('')};
function renderHotels(){const r=$('#hotels');if(!r)return;r.innerHTML='<div class="title"><h2>酒店</h2></div><div class="tripgrid">'+(window.db?.trips?.[0]?'<div class="card"><h3>行程酒店</h3><p>酒店信息跟随行程管理</p></div>':'<div class="empty">暂无酒店</div>')+'</div>'}
function renderTraffic(){const r=$('#traffic');if(!r)return;r.innerHTML='<div class="title"><h2>交通</h2><p>城际交通与导航</p></div><div class="tripgrid"><div class="card"><h3>🚄 城际交通</h3><p>动车 / 高铁 / 飞机信息可以加入具体行程日程。</p><button class="btn" onclick="newTrip()">加入我的行程</button></div><div class="card"><h3>🚕 本地出行</h3><p>打车、公交、地铁、步行路线。</p><button class="btn" onclick="go('trips')">查看行程</button></div></div>'}
window.askAI=async()=>{const input=$('#aiInput'),msg=input?.value.trim();if(!msg)return;$('#messages').insertAdjacentHTML('beforeend',`<div class="msg user">${esc(msg)}</div>`);input.value='';try{const res=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:msg,trip:trip()||null})});const data=await res.json();$('#messages').insertAdjacentHTML('beforeend',`<div class="msg ai">${esc(data.reply||data.message||'AI 暂时没有返回内容')}</div>`)}catch(e){$('#messages').insertAdjacentHTML('beforeend','<div class="msg ai">AI 接口暂时不可用，请稍后再试。</div>')}};
function init(){renderHome();go('home');const m=$('#modal');m?.addEventListener('click',e=>{if(e.target===m)closeModal()});window.addEventListener('pageshow',()=>renderHome())}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();