/* 旅伴旅行管家 · 交互稳定层
 * 只负责：新建行程、城市选择、创建提交、添加日程、推荐填充、弹层关闭。
 * 不改首页/目录/行程详情的既有结构。
 */
(function(){
'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=> 'lv-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);
const toast=m=>window.toast?window.toast(m):alert(m);
const data=()=>window.LVBAN_DATA||{};
const cityName=v=>String(typeof v==='string'?v:(v?.name||v?.city||'')).trim();
function cities(){
 const raw=Array.isArray(data().cities)?data().cities:[];
 const out=raw.map(cityName).filter(Boolean);
 return [...new Set(out)].length?[...new Set(out)]:['北京','上海','广州','深圳','杭州','成都','重庆','西安','福州','平潭','泉州','厦门','南京','苏州','武汉','长沙','青岛','大连','三亚','桂林'];
}
function style(){
 if($('#lvStableStyle'))return;
 const s=document.createElement('style');s.id='lvStableStyle';s.textContent=`
 .lvStableOverlay{position:fixed;inset:0;z-index:30000;background:rgba(20,20,38,.48);display:flex;align-items:flex-end;justify-content:center}
 .lvStableSheet{width:min(720px,100%);max-height:90vh;overflow:auto;background:#f7f8fc;border-radius:28px 28px 0 0;padding:18px;box-shadow:0 -20px 60px rgba(0,0,0,.2)}
 .lvStableHead{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.lvStableHead b{font-size:19px}.lvStableClose{background:#efedff;color:#5d4de5;padding:9px 13px;border-radius:12px;font-weight:800}
 .lvStableSearch{width:100%;height:46px;border:1px solid #e5e2ef;border-radius:14px;padding:0 13px;background:#fff;outline:0}
 .lvStablePicked{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0}.lvStablePicked span{padding:6px 9px;border-radius:10px;background:#efedff;color:#5d4de5;font-size:12px;font-weight:700}
 .lvStableGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;max-height:50vh;overflow:auto;padding:2px}.lvStableCity{padding:11px 7px;border:1px solid #e6e3ef;border-radius:12px;background:#fff;color:#333}.lvStableCity.on{background:#6958f5;color:#fff;border-color:#6958f5}
 .lvStableFoot{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-top:12px;padding-top:12px;border-top:1px solid #e9e7f2}.lvStablePrimary{border:0;background:#6958f5;color:#fff;padding:12px 18px;border-radius:13px;font-weight:900}.lvStablePrimary:disabled{opacity:.45}
 .lvStableForm{display:grid;gap:9px}.lvStableForm label{font-size:12px;color:#77788b;font-weight:700}.lvStableForm input,.lvStableForm textarea{width:100%;box-sizing:border-box;border:1px solid #e5e2ef;border-radius:14px;background:#fff;padding:12px;outline:0}.lvStableForm textarea{min-height:86px;resize:vertical}.lvStableDest{display:flex;gap:8px}.lvStableDest input{flex:1}.lvStableDest button{background:#efedff;color:#5d4de5;border-radius:12px;padding:0 13px;font-weight:800}
 .lvStableModes{display:grid;grid-template-columns:1fr 1fr;gap:8px}.lvStableMode{padding:12px;border:1px solid #e5e2ef;border-radius:14px;background:#fff;text-align:left}.lvStableMode.on{border:2px solid #6958f5;background:#efedff;color:#5d4de5}
 .lvStableRecommend{display:flex;gap:8px;overflow:auto;padding:2px 0 5px}.lvStableRec{flex:0 0 auto;min-width:150px;max-width:220px;padding:9px 11px;border:1px solid #e3e0f4;border-radius:13px;background:#fff;color:#5d4de5;text-align:left}.lvStableRec small{display:block;color:#999;margin-top:4px;white-space:normal}.lvStableHint{font-size:11px;color:#888}
 @media(max-width:700px){.lvStableGrid{grid-template-columns:repeat(3,1fr)}.lvStableModes{grid-template-columns:1fr}}
 `;document.head.appendChild(s);
}
function mainModal(title,html){const m=$('#modal');if(!m)return false;$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;m.classList.add('show');m.style.display='flex';m.setAttribute('aria-hidden','false');return true}
function closeMain(){const m=$('#modal');if(!m)return;m.classList.remove('show');m.style.display='none';m.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
window.closeModal=closeMain;
function cityPicker(selected,onDone){
 style();const o=document.createElement('div');o.className='lvStableOverlay';o.innerHTML=`<div class="lvStableSheet"><div class="lvStableHead"><b>选择目的地</b><button class="lvStableClose" type="button">关闭</button></div><input class="lvStableSearch" placeholder="搜索城市，例如：厦门、福州、成都"><div class="lvStablePicked"></div><div class="lvStableGrid"></div><div class="lvStableFoot"><span class="lvStableHint">支持多选城市</span><button class="lvStablePrimary" type="button">确认选择</button></div></div>`;document.body.appendChild(o);
 const search=o.querySelector('.lvStableSearch'),grid=o.querySelector('.lvStableGrid'),picked=o.querySelector('.lvStablePicked'),confirm=o.querySelector('.lvStablePrimary');let set=new Set(selected||[]);
 const draw=()=>{const q=search.value.trim().toLowerCase();const arr=cities().filter(c=>!q||c.toLowerCase().includes(q));grid.innerHTML=arr.map(c=>`<button type="button" class="lvStableCity ${set.has(c)?'on':''}" data-city="${esc(c)}">${esc(c)}</button>`).join('')||'<div class="lvStableHint">没有找到城市</div>';picked.innerHTML=[...set].map(c=>`<span>${esc(c)}</span>`).join('');confirm.disabled=!set.size};
 search.oninput=draw;grid.onclick=e=>{const b=e.target.closest('[data-city]');if(!b)return;const c=b.dataset.city;set.has(c)?set.delete(c):set.add(c);draw()};o.querySelector('.lvStableClose').onclick=()=>o.remove();o.onclick=e=>{if(e.target===o)o.remove()};confirm.onclick=()=>{onDone([...set]);o.remove()};draw();setTimeout(()=>search.focus(),30);
}
function durationPicker(trip,selected,after){
 const start=new Date(trip.start+'T00:00:00'),end=new Date(trip.end+'T00:00:00');const total=Math.floor((end-start)/86400000)+1;const n=selected.length;let vals=selected.map((_,i)=>Math.floor(total/n)+(i<total%n?1:0));
 style();const o=document.createElement('div');o.className='lvStableOverlay';o.innerHTML=`<div class="lvStableSheet"><div class="lvStableHead"><b>安排每个城市玩几天</b><button class="lvStableClose" type="button">关闭</button></div><div class="lvStableHint" style="margin-bottom:12px">总共 ${total} 天，请把全部天数分配给城市。</div><div class="lvStableForm">${selected.map((c,i)=>`<div style="display:grid;grid-template-columns:1fr 90px;gap:8px;align-items:center"><b>${esc(c)}</b><input class="lvDur" data-city="${esc(c)}" type="number" min="1" max="${total}" value="${vals[i]}"></div>`).join('')}</div><div class="lvStableFoot"><span class="lvStableHint lvDurStatus"></span><button class="lvStablePrimary lvDurOk" type="button">保存</button></div></div>`;document.body.appendChild(o);const inputs=[...o.querySelectorAll('.lvDur')],status=o.querySelector('.lvDurStatus'),ok=o.querySelector('.lvDurOk');const check=()=>{const sum=inputs.reduce((a,x)=>a+(Number(x.value)||0),0);status.textContent=`已分配 ${sum}/${total} 天`;status.style.color=sum===total?'#2d9a6a':'#d94e5c';ok.disabled=sum!==total};inputs.forEach(x=>x.oninput=check);check();o.querySelector('.lvStableClose').onclick=()=>o.remove();ok.onclick=()=>{if(ok.disabled)return;trip.cityDurations=inputs.map(x=>({city:x.dataset.city,days:Number(x.value)}));trip.city=selected.join(' · ');window.save?.();o.remove();after?.()};
}
window.newTrip=function(){
 style();let selected=[],mode='manual';mainModal('新建行程',`<div class="lvStableForm"><label>行程名称</label><input id="ntName" placeholder="例如：国庆厦门慢旅行"><label>目的地</label><div class="lvStableDest"><input id="ntCity" placeholder="点击选择城市，可多选" readonly><button id="lvPickCity" type="button">选择城市</button></div><div id="lvPicked" class="lvStablePicked"></div><label>开始日期</label><input id="ntStart" type="date"><label>结束日期</label><input id="ntEnd" type="date"><label style="display:flex;gap:8px;align-items:center"><input id="ntAlternate" type="checkbox" style="width:auto"> 有备选路线（勾选后才生成 A / B）</label><div class="lvStableModes"><button id="lvManual" class="lvStableMode on" type="button"><b>我自己安排</b><br><small>自己添加日期和日程</small></button><button id="lvAI" class="lvStableMode" type="button"><b>让 AI 帮我规划</b><br><small>创建后进入 AI</small></button></div><button id="lvCreate" class="lvStablePrimary" style="width:100%" type="button">创建行程</button></div>`);
 const cityInput=$('#ntCity'),picked=$('#lvPicked');const refresh=()=>{cityInput.value=selected.join(' · ');picked.innerHTML=selected.map(c=>`<span>${esc(c)}</span>`).join('')};$('#lvPickCity').onclick=()=>cityPicker(selected,x=>{selected=x;refresh()});cityInput.onclick=$('#lvPickCity').onclick;$('#lvManual').onclick=()=>{mode='manual';$('#lvManual').classList.add('on');$('#lvAI').classList.remove('on')};$('#lvAI').onclick=()=>{mode='ai';$('#lvAI').classList.add('on');$('#lvManual').classList.remove('on')};
 $('#lvCreate').onclick=()=>{const name=$('#ntName').value.trim(),start=$('#ntStart').value,end=$('#ntEnd').value,alt=$('#ntAlternate').checked;if(!name||!start||!end)return toast('请填写行程名称和日期');if(end<start)return toast('结束日期不能早于开始日期');if(!selected.length)return toast('请先选择目的地');const days=[];for(let d=new Date(start+'T00:00:00'),i=0;d<=new Date(end+'T00:00:00');d.setDate(d.getDate()+1),i++)days.push({id:uid(),label:'DAY '+(i+1),date:d.toISOString().slice(0,10),title:selected.length===1?'待安排':selected[Math.min(i,selected.length-1)]+' · 待安排',items:[]});const clone=()=>days.map(d=>({...d,id:uid(),items:[]}));const t={id:uid(),name,city:selected.join(' · '),start,end,people:1,hasAlternateRoutes:alt,plans:[{id:'A',name:'方案 A',days:clone()}]};if(alt)t.plans.push({id:'B',name:'方案 B',days:clone()});window.db.trips.push(t);window.activeTrip=t.id;window.activePlan='A';window.activeDay=0;window.save?.();closeMain();window.renderTrips?.();toast(alt?'创建成功：已生成 A / B':'创建成功');if(selected.length>1)durationPicker(t,selected,()=>{window.renderTrips?.()});if(mode==='ai')setTimeout(()=>window.go?.('ai'),250)};
};
function recommendations(city){const c=String(city||'').replace(/市$/,'');const out=[];const add=(type,arr)=>{(Array.isArray(arr)?arr:[]).forEach(x=>{const xc=String(x.city||'').replace(/市$/,'');if(x.name&&(!xc||xc===c))out.push({...x,type})})};add('景点',data().spots);add('美食',data().foods);add('酒店',data().hotels);return out.slice(0,10)}
window.openDayEditor=function(){const p=window.currentPlan?.()||window.db?.trips?.find(x=>x.id===window.activeTrip)?.plans?.find(x=>x.id===window.activePlan);const d=p?.days?.[window.activeDay];if(!d)return toast('请先选择日期');const t=window.currentTrip?.()||window.db?.trips?.find(x=>x.id===window.activeTrip);const citiesForTrip=String(t?.city||'').split(/[·,，、/]/).filter(Boolean);const city=d.city||citiesForTrip[0]||'';mainModal('添加日程',`<div class="lvStableForm"><label>时间</label><input id="diTime" type="time" value="09:00"><label>安排什么？</label><div id="lvRec" class="lvStableRecommend"></div><input id="diName" placeholder="例如：南普陀寺"><label>地址</label><input id="diAddr" placeholder="可复制、可导航的完整地址"><label>备注</label><textarea id="diNote" placeholder="交通、门票、餐饮等"></textarea><button id="lvSaveDay" class="lvStablePrimary" style="width:100%" type="button">加入当天行程</button></div>`);const rec=$('#lvRec'),renderRec=()=>{const arr=recommendations(city);rec.innerHTML=arr.length?arr.map((x,i)=>`<button class="lvStableRec" type="button" data-i="${i}">${esc(x.name)}<small>${esc(x.address||'')}</small></button>`).join(''):'<span class="lvStableHint">当前城市暂无数据库推荐，可直接填写</span>';rec.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{const x=arr[Number(b.dataset.i)];$('#diName').value=x.name||'';$('#diAddr').value=x.address||'';$('#diNote').value=[x.highlight||x.description||x.dishes||'',x.transport?'交通：'+x.transport:''].filter(Boolean).join('\n')})};renderRec();$('#lvSaveDay').onclick=window.saveDayItem};
window.saveDayItem=function(){const p=window.currentPlan?.()||window.db?.trips?.find(x=>x.id===window.activeTrip)?.plans?.find(x=>x.id===window.activePlan),d=p?.days?.[window.activeDay];const n=$('#diName')?.value.trim();if(!d)return toast('当前日期不存在');if(!n)return toast('请填写日程名称');d.items=d.items||[];d.items.push({id:uid(),time:$('#diTime')?.value||'09:00',name:n,address:$('#diAddr')?.value.trim()||'',note:$('#diNote')?.value.trim()||''});d.items.sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));window.save?.();closeMain();window.renderTripDetail?.();toast('已加入当天行程')};
// 关闭主弹层：按钮、遮罩点击、ESC 均可用
function bindClose(){const m=$('#modal');if(!m||m.dataset.lvStableClose)return;m.dataset.lvStableClose='1';m.addEventListener('click',e=>{if(e.target===m)closeMain();const b=e.target.closest('button');if(b&&['关闭','×','✕'].includes((b.textContent||'').trim())){e.preventDefault();e.stopPropagation();closeMain()}});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMain()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindClose);else bindClose();
})();
