/* 旅伴旅行管家 · 最终行程修复层 */
(function(){
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date=v=>{if(!v)return null;const d=new Date(String(v).slice(0,10)+'T00:00:00');return isNaN(d)?null:d};
  const today=()=>{const d=new Date();d.setHours(0,0,0,0);return d};
  const trips=()=>{try{const x=JSON.parse(localStorage.getItem('lvban-trips')||'[]');return Array.isArray(x)?x:[]}catch{return[]}};
  const save=x=>localStorage.setItem('lvban-trips',JSON.stringify(x));
  const hidden=()=>localStorage.getItem('lvban-hidden-default-trip')==='1';

  function css(){if($('#lv-final-style'))return;const s=document.createElement('style');s.id='lv-final-style';s.textContent=`
    .lv-more-wrap{position:absolute;right:12px;top:12px;z-index:30}.lv-more{width:38px;height:34px!important;padding:0!important;border-radius:12px!important;font-size:21px!important;background:#f3f1ff!important;color:#6254e8!important}.lv-menu{position:absolute;right:0;top:40px;min-width:150px;padding:6px;background:#fff;border:1px solid #eeeafa;border-radius:14px;box-shadow:0 12px 30px #302b5a25;display:none;z-index:100}.lv-menu.show{display:block}.lv-menu button{display:block;width:100%;text-align:left;padding:10px 11px;border-radius:10px;background:transparent;color:#333;font-size:13px}.lv-menu .danger-item{color:#d94e5c}.lv-day-x{display:inline-flex;align-items:center;justify-content:center;margin-left:7px;width:21px;height:21px;border-radius:7px;background:#fff0f1;color:#d94e5c;font-weight:900}.lv-countdown{margin-top:16px;padding:15px 16px;border-radius:20px;background:#ffffff20;border:1px solid #ffffff40;color:#fff}.lv-countdown strong{display:block;font-size:34px;font-weight:900}.lv-countdown small{display:block;font-size:12px;margin-top:4px}.lv-new-trip{width:auto!important;min-width:142px!important;padding:0 18px!important;border-radius:20px!important;font-size:15px!important;font-weight:800;white-space:nowrap}.lv-empty{text-align:center;padding:36px 16px;color:#77788b}
  `;document.head.appendChild(s)}

  function countdown(){const hero=$('#home .hero');if(!hero)return;let box=$('#lv-countdown',hero);if(!box){box=document.createElement('div');box.id='lv-countdown';box.className='lv-countdown';hero.appendChild(box)}
    const now=today(), all=[];if(!hidden())all.push({name:'十一福建游',start:'2026-09-28',end:'2026-10-04'});
    trips().forEach(t=>{if(date(t.start))all.push({name:t.name||'我的旅行',start:t.start,end:t.end||t.start})});all.sort((a,b)=>date(a.start)-date(b.start));
    if(!all.length){box.innerHTML='<strong>暂无旅行</strong><small>创建行程后，这里会自动关联最近一次出发。</small>';return}
    const current=all.find(x=>date(x.start)<=now&&date(x.end)>=now), target=current||all.find(x=>date(x.start)>=now)||all[all.length-1];
    if(date(target.start)<=now&&date(target.end)>=now)box.innerHTML='<strong>旅行进行中</strong><small>当前行程：'+esc(target.name)+' · '+esc(target.start)+' 至 '+esc(target.end)+'</small>';
    else box.innerHTML='<strong>'+Math.max(0,Math.ceil((date(target.start)-now)/86400000))+' 天</strong><small>距离最近一次出发 · '+esc(target.name)+' · '+esc(target.start)+'</small>';
  }

  function removeInspiration(){ $$('#trips .tabs .tab').forEach(x=>{if(x.textContent.trim()==='发现灵感')x.remove()}) }
  function oneCreate(){ $$('.float').forEach((x,i)=>{if(i) x.remove()});const b=$('.float');if(b){b.textContent='＋ 新建行程';b.classList.add('lv-new-trip');b.setAttribute('aria-label','新建行程')} $$('#trips button').forEach(x=>{if(!x.classList.contains('float')&&x.textContent.replace(/\s/g,'').includes('新建行程'))x.remove()}) }

  function delDefault(){if(!confirm('确定删除“十一福建游”整个行程？'))return;localStorage.setItem('lvban-hidden-default-trip','1');state.day=0;renderTrips();countdown();toast('行程已删除')}
  function delCustom(i){const a=trips();if(!a[i])return;if(!confirm('确定删除“'+a[i].name+'”整个行程？'))return;a.splice(i,1);save(a);renderTrips();countdown();toast('行程已删除')}
  function more(card,kind,index){if(card.querySelector('.lv-more-wrap'))return;card.style.position='relative';const w=document.createElement('div');w.className='lv-more-wrap';const m=document.createElement('button');m.className='btn lv-more';m.type='button';m.textContent='⋯';const menu=document.createElement('div');menu.className='lv-menu';
    const cp=document.createElement('button');cp.textContent='复制行程信息';cp.onclick=e=>{e.stopPropagation();const t=kind==='default'?{name:'十一福建游',start:'2026-09-28',end:'2026-10-04'}:trips()[index];navigator.clipboard?.writeText([t?.name,t?.start,t?.end].filter(Boolean).join(' · '));menu.classList.remove('show');toast('已复制行程信息')};
    const fav=document.createElement('button');fav.textContent='收藏';fav.onclick=e=>{e.stopPropagation();localStorage.setItem('lvban-fav-'+kind+'-'+index,'1');menu.classList.remove('show');toast('已收藏')};
    const del=document.createElement('button');del.textContent='删除行程';del.className='danger-item';del.onclick=e=>{e.stopPropagation();menu.classList.remove('show');kind==='default'?delDefault():delCustom(index)};
    menu.append(cp,fav,del);w.append(m,menu);card.appendChild(w);m.onclick=e=>{e.stopPropagation();$$('.lv-menu.show').forEach(x=>x!==menu&&x.classList.remove('show'));menu.classList.toggle('show')};
  }

  function newTrip(){modal('新建行程',`<div class="form"><label>行程名称</label><input id="tName" placeholder="例如：十一福建游"><label>开始日期</label><input id="tStart" type="date"><label>结束日期</label><input id="tEnd" type="date"><label>城市 / 地区</label><input id="tCity" placeholder="例如：福州 / 平潭 / 泉州 / 厦门"><label style="display:flex;align-items:center;gap:8px;padding:8px 0"><input id="tBackup" type="checkbox" style="width:auto"> 是否有备选路线</label><div class="muted">未勾选：只创建一条路线；勾选后才会出现方案 A / 方案 B。</div><button class="btn primary" onclick="lvSaveTrip()">创建行程</button></div>`)}
  function makeDays(s,e){const a=[],x=date(s),y=date(e);if(!x||!y||y<x)return a;for(let d=new Date(x);d<=y;d.setDate(d.getDate()+1))a.push({date:d.toISOString().slice(0,10),title:'待安排',items:[]});return a}
  function lvSaveTrip(){const name=$('#tName').value.trim(),start=$('#tStart').value,end=$('#tEnd').value,city=$('#tCity').value.trim(),hasBackup=$('#tBackup').checked;if(!name||!start||!end)return toast('请先填写行程名称和日期');if(date(end)<date(start))return toast('结束日期不能早于开始日期');const d=makeDays(start,end),t={id:'trip_'+Date.now(),name,start,end,city,hasBackup,plan:'A',schedulesA:d,schedulesB:hasBackup?JSON.parse(JSON.stringify(d)):null};const a=trips();a.push(t);save(a);closeModal();renderTrips();countdown();toast('行程已创建')}

  function customIndex(){return Number(window.__lvCustomIndex)}
  function custom(){return trips()[customIndex()]}
  function arr(){const t=custom();if(!t)return[];return window.__lvCustomPlan==='B'&&t.hasBackup?(t.schedulesB||(t.schedulesB=t.schedulesA.map(x=>({...x,items:JSON.parse(JSON.stringify(x.items||[]))})))):t.schedulesA||[]}
  function persist(t){const a=trips();a[customIndex()]=t;save(a)}
  function openCustom(i){window.__lvCustomIndex=i;window.__lvCustomPlan='A';window.__lvCustomDay=0;renderCustom()}
  function renderCustom(){const t=custom();if(!t){renderTrips();return}const a=arr(),day=Math.max(0,Math.min(Number(window.__lvCustomDay||0),a.length-1));window.__lvCustomDay=day;const d=a[day];tripList.innerHTML='';if(!a.length){tripDetail.innerHTML='<div class="panel"><h2>'+esc(t.name)+'</h2><div class="lv-empty">暂无日期</div></div>';return}
    tripDetail.innerHTML='<div class="panel" style="margin-top:14px"><div class="detailbar"><div><h2 style="margin:0">'+esc(t.name)+'</h2><div class="muted">'+esc(t.city||'')+' · '+esc(t.start)+' → '+esc(t.end)+'</div></div><div style="display:flex;gap:8px"><button class="btn primary" onclick="lvAddEvent()">＋ 添加日程</button><button class="btn danger" onclick="lvDeleteDay()">删除当天</button></div></div>'+(t.hasBackup?'<div class="plans"><button class="plan '+(window.__lvCustomPlan==='A'?'on':'')+'" onclick="window.__lvCustomPlan=\'A\';window.__lvCustomDay=0;renderCustom()"><b>方案 A</b><small>主路线</small></button><button class="plan '+(window.__lvCustomPlan==='B'?'on':'')+'" onclick="window.__lvCustomPlan=\'B\';window.__lvCustomDay=0;renderCustom()"><b>方案 B</b><small>备选路线</small></button></div>':'')+'<div class="days">'+a.map((x,i)=>'<button class="day '+(i===day?'on':'')+'" onclick="window.__lvCustomDay='+i+';renderCustom()"><b>'+esc(x.date)+'</b><small>DAY '+(i+1)+'</small><span class="lv-day-x" onclick="event.stopPropagation();window.__lvCustomDay='+i+';lvDeleteDay()">×</span></button>').join('')+'</div><div class="card"><h2 style="margin:0">'+esc(d.title||'待安排')+'</h2><div class="muted">当天详细行程</div></div><div class="timeline">'+((d.items||[]).map((x,i)=>'<div class="event card"><div class="event-time">'+esc(x[0]||'—')+'</div><h3>'+esc(x[1]||'未命名')+'</h3><div class="addr">📍 '+esc(x[2]||'')+'</div><div class="muted" style="margin-top:5px">'+esc(x[3]||'')+'</div><div class="actions"><button class="btn" onclick="lvEditEvent('+i+')">编辑</button><button class="btn danger" onclick="lvDeleteEvent('+i+')">删除</button></div></div>').join('')||'<div class="lv-empty">今天还没有安排，点击“＋ 添加日程”开始添加。</div>')+'</div></div>';
  }
  function lvDeleteDay(){const t=custom(),a=arr(),i=Number(window.__lvCustomDay||0);if(!t||!a[i])return;if(a.length<=1)return alert('至少保留一天行程。如果不需要这个旅行，请删除整个行程。');if(!confirm('确定删除“'+a[i].date+'”整天行程？'))return;a.splice(i,1);window.__lvCustomDay=Math.max(0,Math.min(i,a.length-1));persist(t);renderCustom();countdown()}
  function lvDeleteEvent(i){const t=custom(),a=arr(),d=a[Number(window.__lvCustomDay||0)];if(!d)return;if(!confirm('确定删除这条详细日程？'))return;d.items.splice(i,1);persist(t);renderCustom()}
  function lvAddEvent(){modal('添加日程',`<div class="form"><label>时间</label><input id="cxTime" type="time" value="09:00"><label>名称</label><input id="cxName"><label>地址</label><input id="cxAddr"><label>备注</label><textarea id="cxNote"></textarea><button class="btn primary" onclick="lvSaveEvent()">加入当天</button></div>`)}
  function lvSaveEvent(){const t=custom(),a=arr(),d=a[Number(window.__lvCustomDay||0)];d.items.push([$('#cxTime').value,$('#cxName').value,$('#cxAddr').value,$('#cxNote').value]);d.items.sort((x,y)=>String(x[0]).localeCompare(String(y[0])));persist(t);closeModal();renderCustom()}
  function lvEditEvent(i){const t=custom(),d=arr()[Number(window.__lvCustomDay||0)],x=d?.items?.[i];if(!x)return;modal('编辑日程',`<div class="form"><label>时间</label><input id="cxTime" type="time" value="${esc(x[0])}"><label>名称</label><input id="cxName" value="${esc(x[1])}"><label>地址</label><input id="cxAddr" value="${esc(x[2])}"><label>备注</label><textarea id="cxNote">${esc(x[3])}</textarea><button class="btn primary" onclick="lvSaveEdit(${i})">保存</button></div>`)}
  function lvSaveEdit(i){const t=custom(),d=arr()[Number(window.__lvCustomDay||0)];d.items[i]=[$('#cxTime').value,$('#cxName').value,$('#cxAddr').value,$('#cxNote').value];persist(t);closeModal();renderCustom()}

  function renderDefaultDetail(){if(typeof detailDefault==='function')tripDetail.innerHTML=detailDefault();decorateDefault()}
  function deleteDefaultDay(){const a=schedules[state.plan],i=Number(state.day||0);if(a.length<=1)return alert('至少保留一天行程。如果不需要这个旅行，请删除整个行程。');if(!confirm('确定删除“'+(a[i]?.date||'当天')+'”整天行程？'))return;a.splice(i,1);state.day=Math.max(0,Math.min(i,a.length-1));renderTrips()}
  function deleteDefaultEvent(i){const a=schedules[state.plan],d=a[state.day];if(!d)return;if(!confirm('确定删除这条详细日程？'))return;d.items.splice(i,1);renderTrips()}
  function decorateDefault(){const bar=$('.detailbar',tripDetail);if(!bar)return;let b=$('.lv-dd',bar);if(!b){b=document.createElement('button');b.className='btn danger lv-dd';b.textContent='删除当天';b.onclick=deleteDefaultDay;bar.appendChild(b)}$$('.days .day',tripDetail).forEach((x,i)=>{if(x.querySelector('.lv-day-x'))return;const z=document.createElement('span');z.className='lv-day-x';z.textContent='×';z.onclick=e=>{e.stopPropagation();state.day=i;deleteDefaultDay()};x.appendChild(z)});$$('.timeline .event',tripDetail).forEach((x,i)=>{const a=$('.actions:last-child',x);if(!a)return;[...a.querySelectorAll('button')].filter(b=>b.textContent.trim()==='删除').forEach(b=>b.remove());const d=document.createElement('button');d.className='btn danger';d.textContent='删除';d.onclick=e=>{e.stopPropagation();deleteDefaultEvent(i)};a.appendChild(d)})}

  function renderTrips(){removeInspiration();oneCreate();const list=$('#tripList'),detail=$('#tripDetail');if(!list||!detail)return;const html=[];if(!hidden())html.push('<div class="card tripcard"><span class="badge">旅行计划</span><h2>十一福建游</h2><div class="muted">福州 · 平潭 · 泉州 · 厦门</div><div class="muted" style="margin-top:12px">2026-09-28 → 2026-10-04</div><div class="actions"><button class="btn primary" onclick="openDefault()">打开行程</button></div></div>');trips().forEach((t,i)=>html.push('<div class="card tripcard"><span class="badge">我的行程</span><h2>'+esc(t.name)+'</h2><div class="muted">'+esc(t.start)+' → '+esc(t.end)+'</div><div class="muted">'+esc(t.city||'')+'</div><div class="actions"><button class="btn primary" onclick="lvOpenCustom('+i+')">打开</button><button class="btn" onclick="lvEditTrip('+i+')">编辑</button></div></div>'));list.innerHTML=html.length?'<div class="tripgrid">'+html.join('')+'</div>':'<div class="lv-empty">还没有行程，点击右下角“＋ 新建行程”创建。</div>';
    $$('#tripList .tripcard').forEach((c,i)=>{const isDef=!hidden()&&i===0;more(c,isDef?'default':'custom',isDef?0:i-(hidden()?0:1))});
    if(window.__lvCustomIndex!==undefined&&custom())renderCustom();else renderDefaultDetail();countdown();
  }
  function lvOpenCustom(i){openCustom(i)}
  function lvEditTrip(i){const t=trips()[i];modal('编辑行程',`<div class="form"><label>行程名称</label><input id="etName" value="${esc(t.name)}"><label>开始日期</label><input id="etStart" type="date" value="${esc(t.start)}"><label>结束日期</label><input id="etEnd" type="date" value="${esc(t.end)}"><label>城市 / 地区</label><input id="etCity" value="${esc(t.city||'')}"><button class="btn primary" onclick="lvSaveEditTrip(${i})">保存</button><button class="btn danger" onclick="delCustom(${i})">删除这个行程</button></div>`)}
  function lvSaveEditTrip(i){const a=trips(),t=a[i];t.name=$('#etName').value.trim();t.start=$('#etStart').value;t.end=$('#etEnd').value;t.city=$('#etCity').value.trim();save(a);closeModal();renderTrips();countdown()}

  function patch(){window.newTrip=newTrip;window.lvSaveTrip=lvSaveTrip;window.lvOpenCustom=lvOpenCustom;window.lvEditTrip=lvEditTrip;window.lvSaveEditTrip=lvSaveEditTrip;window.lvDeleteDay=lvDeleteDay;window.lvDeleteEvent=lvDeleteEvent;window.lvAddEvent=lvAddEvent;window.lvSaveEvent=lvSaveEvent;window.lvEditEvent=lvEditEvent;window.lvSaveEdit=lvSaveEdit;window.renderTrips=renderTrips}
  function run(){css();patch();renderTrips();countdown()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else setTimeout(run,0);
  setTimeout(run,300);setTimeout(run,1000);
  document.addEventListener('click',e=>{if(!e.target.closest('.lv-more-wrap'))$$('.lv-menu.show').forEach(x=>x.classList.remove('show'))});
})();
