/* 旅伴旅行管家 Pro · 智能日程增强 v3 */
(function(){
  'use strict';
  function migrate(){try{var a=JSON.parse(localStorage.getItem('lvban-trips')||'[]');if(!Array.isArray(a))return;var changed=false;a.forEach(function(t){if(typeof t.hasBackup!=='boolean'){t.hasBackup=!!t.hasAlternateRoutes;changed=true;}if(!t.hasBackup)t.schedulesB=null;if(Array.isArray(t.plans))t.plans.forEach(function(p){(p.days||[]).forEach(function(day){if(!Array.isArray(day.items)){day.items=[];changed=true;}})});});if(changed)localStorage.setItem('lvban-trips',JSON.stringify(a));}catch(e){}}
  function source(){var d=window.LVBAN_DATA||{},out=[];(Array.isArray(d.spots)?d.spots:[]).forEach(function(x){if(x&&x.name)out.push({type:'景点',city:x.city||'',name:x.name,address:x.address||'',note:x.highlight||'',transport:x.transport||''});});(Array.isArray(d.foods)?d.foods:[]).forEach(function(x){if(x&&x.name)out.push({type:'美食',city:x.city||'',name:x.name,address:x.address||'',note:x.highlight||'',transport:x.transport||''});});return out;}
  function tripCities(){try{var t=window.currentTrip&&window.currentTrip(),raw=t&&t.city||'',known=(window.LVBAN_DATA&&window.LVBAN_DATA.cities)||['福州','平潭','泉州','厦门'],out=[];known.forEach(function(c){if(raw.indexOf(c)>=0)out.push(c);});if(!out.length&&raw)out=[raw];return out;}catch(e){return [];}}
  function activeDay(){try{return window.currentPlan&&window.currentPlan()?.days?.[window.activeDay]||null;}catch(e){return null;}}
  function currentCity(){var d=activeDay();if(d&&d.city)return d.city;try{var t=window.currentTrip&&window.currentTrip(),title=(d&&d.title)||'',cs=tripCities();for(var i=0;i<cs.length;i++)if(title.indexOf(cs[i])>=0)return cs[i];if(cs.length===1)return cs[0];if(t&&t.currentCity)return t.currentCity;}catch(e){}return '';}
  function fullAddress(x,city){var a=String(x&&x.address||'').trim();if(!a)return '';if(/省|市|区|县|镇|乡|街|路|号/.test(a)&&(a.indexOf('市')>=0||a.indexOf('省')>=0||a.indexOf('县')>=0||a.indexOf('区')>=0)){if(city==='平潭'&&a.indexOf('福建')<0&&a.indexOf('福州')<0)return '福建省福州市'+a;if(city==='福州'&&a.indexOf('福建')<0&&a.indexOf('福州')<0)return '福建省福州市'+a;if(city==='泉州'&&a.indexOf('福建')<0&&a.indexOf('泉州')<0&&a.indexOf('石狮')<0)return '福建省泉州市'+a;if(city==='厦门'&&a.indexOf('福建')<0&&a.indexOf('厦门')<0)return '福建省厦门市'+a;return a;}if(city==='福州')return '福建省福州市'+a;if(city==='平潭')return a.indexOf('平潭')===0?'福建省福州市'+a:'福建省福州市平潭县'+a;if(city==='泉州')return '福建省泉州市'+a;if(city==='厦门')return '福建省厦门市'+a;return city?a+'（'+city+'）':a;}
  function matches(q,city){var s=source(),qq=String(q||'').trim().toLowerCase(),c=city||currentCity(),arr=s.filter(function(x){if(c&&x.city&&x.city!==c)return false;if(!qq)return true;return (x.name+' '+x.address+' '+x.city).toLowerCase().indexOf(qq)>=0;});if(!arr.length&&qq)arr=s.filter(function(x){return (x.name+' '+x.address+' '+x.city).toLowerCase().indexOf(qq)>=0;});return arr;}
  function installStyle(){if(document.getElementById('lvbanSmartEventStyle'))return;var st=document.createElement('style');st.id='lvbanSmartEventStyle';st.textContent='.lvban-smart-wrap{margin:0 0 8px;padding:10px 0}.lvban-smart-title{font-size:12px;color:#77788b;font-weight:700;margin-bottom:7px}.lvban-smart-city{width:100%;padding:10px 12px;border:1px solid #e4e1f5;border-radius:14px;background:#fff;color:#333;margin-bottom:8px}.lvban-smart-recommend{display:flex;flex-wrap:wrap;gap:8px;position:relative;z-index:3}.lvban-smart-recommend button{display:block;position:relative;z-index:4;pointer-events:auto;min-width:130px;padding:8px 11px;border:1px solid #e4e1f5;border-radius:13px;background:#fff;color:#5d4de5;font-size:12px;font-weight:700;cursor:pointer;text-align:left}.lvban-smart-recommend button:hover{background:#efedff}.lvban-smart-recommend button:active{transform:scale(.98)}.lvban-smart-meta{display:block;font-size:10px;color:#999;margin-top:2px;font-weight:500}.lvban-smart-match{font-size:11px;color:#6958f5;margin:-2px 0 7px;line-height:1.5}';document.head.appendChild(st);}
  function enhanceEventForm(){var body=document.getElementById('modalBody'),title=document.getElementById('modalTitle');if(!body||!title||String(title.textContent||'').trim()!=='添加日程')return;var name=document.getElementById('diName'),addr=document.getElementById('diAddr');if(!name||!addr)return;installStyle();var old=document.getElementById('lvbanSmartWrap');if(old)old.remove();var oldMatch=document.getElementById('lvbanMatchText');if(oldMatch)oldMatch.remove();var cities=tripCities(),selected=currentCity()||cities[0]||'',wrap=document.createElement('div');wrap.id='lvbanSmartWrap';wrap.className='lvban-smart-wrap';var cityLabel=document.createElement('div');cityLabel.className='lvban-smart-title';cityLabel.textContent='智能推荐 · '+(selected||'当前目的地');wrap.appendChild(cityLabel);var citySelect=null;if(cities.length>1){citySelect=document.createElement('select');citySelect.className='lvban-smart-city';cities.forEach(function(c){var o=document.createElement('option');o.value=c;o.textContent=c;o.selected=c===selected;citySelect.appendChild(o);});wrap.appendChild(citySelect);}var list=document.createElement('div');list.className='lvban-smart-recommend';wrap.appendChild(list);name.parentNode.insertBefore(wrap,name);
    function selectedCity(){return citySelect?citySelect.value:selected;}
    function setField(el,value){if(!el)return;el.value=value||'';try{el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));}catch(e){var ev=document.createEvent('HTMLEvents');ev.initEvent('input',true,true);el.dispatchEvent(ev);}}
    function setValue(x){var c=x.city||selectedCity();setField(name,x.name||'');setField(addr,fullAddress(x,c));var note=document.getElementById('diNote');if(note&&!note.value){var n=[];if(x.note)n.push(x.note);if(x.transport)n.push('交通：'+x.transport);setField(note,n.join('\n'));}try{var d=activeDay();if(d&&c)d.city=c;}catch(e){}var m=document.getElementById('lvbanMatchText');if(m)m.remove();m=document.createElement('div');m.id='lvbanMatchText';m.className='lvban-smart-match';m.textContent='✓ 已选择：'+c+' · '+x.name+'｜完整地址已自动填入';addr.parentNode.insertBefore(m,addr);}
    function render(q){var c=selectedCity(),r=matches(q,c).slice(0,6);list.innerHTML='';if(!q){var lb=document.createElement('span');lb.className='lvban-smart-meta';lb.textContent=c?'根据 '+c+' 推荐':'请选择城市后推荐';list.appendChild(lb);}r.forEach(function(x){var b=document.createElement('button');b.type='button';b.setAttribute('data-lvban-smart-name',x.name);b.setAttribute('data-lvban-smart-city',x.city||c);b.setAttribute('data-lvban-smart-address',fullAddress(x,c));b.textContent=x.name;b.title=fullAddress(x,c);var small=document.createElement('span');small.className='lvban-smart-meta';small.textContent=fullAddress(x,c);b.appendChild(small);list.appendChild(b);});if(!r.length){var t=document.createElement('span');t.className='lvban-smart-meta';t.textContent='暂无本地匹配，可继续手动填写';list.appendChild(t);}}
    if(citySelect)citySelect.addEventListener('change',function(){selected=citySelect.value;cityLabel.textContent='智能推荐 · '+selected;render(name.value);});
    if(!name.dataset.lvbanSmartBound){name.dataset.lvbanSmartBound='1';name.addEventListener('input',function(){render(name.value);});name.addEventListener('blur',function(){var q=name.value.trim().toLowerCase();if(!q)return;var r=matches(q,selectedCity()),exact=r.find(function(x){return String(x.name||'').toLowerCase()===q;});if(exact)setValue(exact);else if(r.length===1&&q.length>=2)setValue(r[0]);});}
    if(!wrap.dataset.lvbanSmartClickBound){wrap.dataset.lvbanSmartClickBound='1';list.addEventListener('pointerdown',function(e){var b=e.target.closest('button[data-lvban-smart-name]');if(!b)return;e.preventDefault();e.stopPropagation();var n=b.getAttribute('data-lvban-smart-name')||'';var c=b.getAttribute('data-lvban-smart-city')||selectedCity();var a=b.getAttribute('data-lvban-smart-address')||'';var r=matches(n,c);var x=r.find(function(item){return item.name===n&&item.city===c})||r.find(function(item){return item.name===n})||{name:n,city:c,address:a};setValue(x);});list.addEventListener('click',function(e){var b=e.target.closest('button[data-lvban-smart-name]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();var n=b.getAttribute('data-lvban-smart-name')||'';var c=b.getAttribute('data-lvban-smart-city')||selectedCity();var a=b.getAttribute('data-lvban-smart-address')||'';var r=matches(n,c);var x=r.find(function(item){return item.name===n&&item.city===c})||r.find(function(item){return item.name===n})||{name:n,city:c,address:a};setValue(x);});}
    render('');
  }
  function observe(){if(!document.body)return;var run=function(){setTimeout(enhanceEventForm,30);};new MutationObserver(run).observe(document.body,{subtree:true,childList:true});setInterval(enhanceEventForm,600);run();}
  migrate();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',observe);else observe();
})();
