/* 旅伴旅行管家 Pro · 正式交互修复层 */
(function(){
  const D=window.LVBAN_DATA||{cities:['福州','平潭','泉州','厦门'],spots:[],foods:[]};
  const safe=t=>String(t??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const copy=t=>{t=String(t||'');(navigator.clipboard?navigator.clipboard.writeText(t):Promise.reject()).then(()=>toast('已复制')).catch(()=>{const a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove();toast('已复制')})};
  const nav=t=>{t=String(t||'').trim();if(!t)return toast('暂无地址');window.open('https://www.amap.com/search?query='+encodeURIComponent(t),'_blank','noopener')};
  const toast=t=>{let x=document.getElementById('lv-toast');if(!x){x=document.createElement('div');x.id='lv-toast';x.style='position:fixed;left:50%;bottom:92px;transform:translateX(-50%);z-index:100;padding:11px 16px;border-radius:16px;background:rgba(20,20,35,.9);color:#fff;font-size:13px;opacity:0;transition:.2s';document.body.appendChild(x)}x.textContent=t;x.style.opacity=1;clearTimeout(x._t);x._t=setTimeout(()=>x.style.opacity=0,1600)};
  window.closeModal=()=>document.getElementById('modal').classList.remove('show');
  window.LvbanCopy=copy;window.LvbanNav=nav;
  function mergeCatalog(){
    const spots=D.spots||[],foods=D.foods||[];
    if(!db.spots.length)db.spots=spots.map(x=>({...x,desc:x.highlight||x.avoid||''}));
    if(!db.foods.length)db.foods=foods.map(x=>({...x,desc:x.dishes||x.must||x.recommend||''}));
    const byName=new Map([...spots,...foods].map(x=>[x.name,x]));
    db.spots.forEach(x=>{const y=byName.get(x.name);if(y){x.address=y.address;x.city=y.city;x.transport=y.transport;x.price=y.price;x.highlight=y.highlight;x.avoid=y.avoid}});
    db.foods.forEach(x=>{const y=byName.get(x.name);if(y){x.address=y.address;x.city=y.city;x.transport=y.transport;x.price=y.price;x.dishes=y.dishes;x.must=y.must}});
    if(!db.hotels.length)db.hotels=[['方案A','9月28日','锦江都城酒店（福州三坊七巷东街口地铁站店）','福州市鼓楼区省府路9号','福州'],['方案A','9月29日','维也纳酒店（福州平潭龙王头沙滩店）','平潭县海坛街道西航路190号','平潭'],['方案A','9月30日','丽怡酒店（平潭国际旅游岛店）','平潭县金井大道东段129-11号','平潭'],['方案A','备选','希岸酒店（福州平潭龙王头沙滩店）','平潭县万宝中路158号','平潭'],['方案A','10月1日','维也纳酒店（泉州古城浦西万达店）','泉州市丰泽区泉秀街768号','泉州'],['方案A','10月2-3日','希岸酒店（厦门火车站万象城店）','厦门市思明区厦禾路982号','厦门']].map(x=>({id:uid(),plan:x[0],date:x[1],name:x[2],address:x[3],city:x[4]}));
    save();
  }
  function normalizeItems(){
    const all=[...(D.spots||[]),...(D.foods||[])];const find=n=>all.find(x=>x.name===n||n.includes(x.name)||x.name.includes(n));
    db.trips.forEach(t=>(t.plans||[]).forEach(p=>(p.days||[]).forEach(d=>(d.items||[]).forEach(i=>{const hit=find(i.name);if(hit){i.name=hit.name;i.address=hit.address||i.address;i.city=hit.city||i.city;i.type=i.type|| (D.foods.includes(hit)?'美食':'景点')}}))));
    save();
  }
  function cityCards(arr,type){return arr.map(x=>`<div class="data-card glass"><div class="data-top"><div><div class="city-label">${safe(x.city)}</div><h3>${safe(x.name)}</h3><div class="data-meta">📍 ${safe(x.address||'暂无地址')}</div></div><div class="pill">${safe(type==='food'?'¥'+(x.price||0):(x.price||''))}</div></div><div class="data-desc">${safe(x.highlight||x.dishes||x.must||x.desc||'')}</div><div class="data-meta">🚇 ${safe(x.transport||'')}</div><div class="data-actions"><button class="mini" onclick='LvbanCopy(${JSON.stringify(x.name)})'>复制名称</button><button class="mini" onclick='LvbanCopy(${JSON.stringify(x.address||'')})'>复制地址</button><button class="mini" onclick='LvbanNav(${JSON.stringify(x.address||x.name)})'>导航</button><button class="mini primary" onclick='addCatalog(${JSON.stringify(type)},${JSON.stringify(x.id)})'>加入行程</button></div></div>`).join('')}
  function grouped(container,arr,type){const cities=['福州','平潭','泉州','厦门'];container.innerHTML=cities.map(c=>{const a=arr.filter(x=>x.city===c);return `<section><div class="section-title"><h2>${c}</h2><span class="pill">${a.length} 项</span></div>${cityCards(a.slice(0,6),type)}</section>`}).join('')}
  window.renderHome=()=>{grouped(document.getElementById('homeSpots'),db.spots,'spot');grouped(document.getElementById('homeFoods'),db.foods,'food')};
  window.renderSpots=()=>{const tabs=document.getElementById('spotCities');const list=document.getElementById('spotList');tabs.innerHTML=['全部','福州','平潭','泉州','厦门'].map(c=>`<button class="tab ${spotCity===c?'on':''}" onclick="spotCity='${c}';renderSpots()">${c}</button>`).join('');list.innerHTML=(spotCity==='全部'?db.spots:db.spots.filter(x=>x.city===spotCity)).map(x=>cityCards([x],'spot')).join('')};
  window.renderFoods=()=>{const tabs=document.getElementById('foodCities');const list=document.getElementById('foodList');tabs.innerHTML=['全部','福州','平潭','泉州','厦门'].map(c=>`<button class="tab ${foodCity===c?'on':''}" onclick="foodCity='${c}';renderFoods()">${c}</button>`).join('');list.innerHTML=(foodCity==='全部'?db.foods:db.foods.filter(x=>x.city===foodCity)).map(x=>cityCards([x],'food')).join('')};
  window.addCatalog=addCatalog;
  function addCatalog(type,id){const src=type==='food'?db.foods:db.spots,x=src.find(a=>a.id===id);if(!x)return;const t=currentTrip(),p=currentPlan(),d=p.days[activeDay]||p.days[0];d.items.push({id:uid(),time:'09:00',type:type==='food'?'美食':'景点',name:x.name,address:x.address||'',city:x.city||'',budget:Number(x.price)||0});d.items.sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));save();go('trips');toast('已加入当前 DAY')}
  let spotCity='全部',foodCity='全部';
  const oldGo=window.go;window.go=function(id){oldGo(id);if(id==='home')renderHome();if(id==='spots')renderSpots();if(id==='food')renderFoods()};
  function currentTrip(){return db.trips.find(x=>x.id===activeTrip)||db.trips[0]}
  function currentPlan(){const t=currentTrip();return t.plans.find(x=>x.id===activePlan)||t.plans[0]}
  function actionButtons(i){const a=i.address||'';return `<div class="actions"><button class="mini" onclick='LvbanCopy(${JSON.stringify(i.name)})'>复制名称</button><button class="mini" onclick='LvbanCopy(${JSON.stringify(a)})'>复制地址</button><button class="mini" onclick='LvbanNav(${JSON.stringify(a)})'>导航</button><button class="mini" onclick='openItemEditor(${i._index})'>编辑</button><button class="mini danger" onclick='deleteItem(${i._index})'>删除</button></div>`}
  window.renderTripDetail=function(){const t=currentTrip(),p=currentPlan(),box=document.getElementById('tripDetail');if(!t||!p||!box)return;box.innerHTML=`<div class="scheme-head"><div><div class="crumb">${safe(t.name)} / ${safe(p.name)}</div><div class="scheme-name">${safe(p.name)}</div><div class="sub">${safe(t.city||'多城市旅行')} · ${t.people||1}人</div></div><div class="actions"><button class="mini" onclick="openPlanEditor()">方案管理</button><button class="mini primary" onclick="openDayEditor()">＋ 添加日程</button></div></div><div class="tabs" style="margin-top:10px">${t.plans.map(x=>`<button class="tab ${x.id===activePlan?'on':''}" onclick="switchPlan('${x.id}')">方案 ${x.id}</button>`).join('')}</div><div class="day-tabs">${p.days.map((d,k)=>`<button class="day-tab ${k===activeDay?'on':''}" onclick="activeDay=${k};renderTripDetail()"><b>${d.label}</b><small>${d.date}</small></button>`).join('')}</div><div class="card glass"><div class="crumb">${safe(p.days[activeDay].date)}</div><h3>${safe(p.days[activeDay].title)}</h3><div class="sub">每天独立编辑 · 景点 / 美食 / 酒店 / 火车 / 航班 / 交通 / 备注</div></div><div class="timeline">${p.days[activeDay].items.length?p.days[activeDay].items.map((i,k)=>{i._index=k;return `<div class="it-card glass"><div class="it-time">${safe(i.time||'未定时间')} <span class="it-type">${safe(i.type||'日程')}</span></div><div class="it-title">${safe(i.name)}</div><div class="it-address">📍 ${safe(i.address||'暂无地址')}</div>${i.budget?`<div class="data-meta">预算 ¥${i.budget}</div>`:''}${actionButtons(i)}</div>`}).join(''):'<div class="empty glass">今天还没有详细日程<br><button class="mini primary" style="margin-top:10px" onclick="openDayEditor()">＋ 添加第一条</button></div>'}</div><div class="day-footer"><span class="budget">当天预算：¥${p.days[activeDay].items.reduce((s,x)=>s+Number(x.budget||0),0)}</span><button class="mini primary" onclick="openDayEditor()">＋ 添加</button></div>`}
  window.renderTrips=function(){document.getElementById('tripList').innerHTML=db.trips.map(t=>`<button class="trip-card ${t.id===activeTrip?'active':''}" onclick="selectTrip('${t.id}')"><strong>${safe(t.name)}</strong><small>${safe(t.city||'多城市')}<br>${safe(t.start||'')} → ${safe(t.end||'')}</small></button>`).join('')+`<button class="trip-card" onclick="openNewTrip()"><strong>＋ 新建行程</strong><small>只填写基础信息，自动生成 DAY</small></button>`;renderTripDetail()};
  mergeCatalog();normalizeItems();renderHome();renderSpots();renderFoods();renderTrips();
  const baseRenderTrips=window.renderTrips;
  window.deleteTrip=function(id){const t=(db.trips||[]).find(x=>x.id===id);if(!t)return;if((db.trips||[]).length<=1){toast('至少保留一个行程');return;}if(!confirm('确定删除「'+(t.name||'这个行程')+'」吗？删除后不可恢复。'))return;db.trips=db.trips.filter(x=>x.id!==id);activeTrip=db.trips[0]?.id||null;const first=db.trips[0];activePlan=first?.plans?.[0]?.id||null;activeDay=0;save();baseRenderTrips();toast('行程已删除');};
  window.renderTrips=function(){baseRenderTrips();const list=document.getElementById('tripList');if(!list)return;const bar=document.createElement('div');bar.className='trip-list-actions';bar.style='display:flex;justify-content:flex-end;gap:8px;margin:0 0 12px;position:sticky;top:66px;z-index:10';bar.innerHTML='<button class="mini primary" style="padding:11px 16px;border-radius:14px;box-shadow:0 8px 20px rgba(105,88,245,.18)" onclick="openNewTrip()">＋ 新建行程</button>';list.parentNode.insertBefore(bar,list);list.querySelectorAll('.trip-card').forEach((card,index)=>{if(index >= (db.trips||[]).length)return;const t=db.trips[index];card.style.position='relative';card.style.paddingRight='72px';const del=document.createElement('button');del.className='mini danger trip-delete';del.textContent='删除';del.style='position:absolute;right:10px;top:50%;transform:translateY(-50%);padding:7px 9px;border-radius:10px;z-index:3';del.onclick=(ev)=>{ev.preventDefault();ev.stopPropagation();deleteTrip(t.id)};card.appendChild(del);});};
})();
(function(){const s=document.createElement('script');s.src='itinerary-layout-final.js?v=20260813-3';s.onload=()=>window.lvCityDateLayout?.render?.();document.head.appendChild(s);})();
