(function(){
 const D=window.LVBAN_DATA||{cities:[],spots:[],foods:[]};let spotCity='福州',foodCity='福州',activePlan='A',selectedDay=0;
 const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
 const toast=t=>{let x=document.getElementById('lv-toast');if(!x){x=document.createElement('div');x.id='lv-toast';x.style='position:fixed;left:50%;bottom:92px;transform:translateX(-50%);z-index:100;padding:11px 16px;border-radius:16px;background:rgba(20,20,35,.86);color:#fff;font-size:13px;opacity:0;transition:.22s';document.body.appendChild(x)}x.textContent=t;x.style.opacity=1;clearTimeout(x._t);x._t=setTimeout(()=>x.style.opacity=0,1800)};
 const nav=q=>window.open('https://www.amap.com/search?query='+encodeURIComponent(q),'_blank','noopener');
 const copy=t=>navigator.clipboard?.writeText(t).then(()=>toast('已复制')).catch(()=>{const a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove();toast('已复制')});
 function modal(html){const m=document.getElementById('modal'),s=document.getElementById('sheet');if(!m||!s)return;s.innerHTML=html;m.classList.add('show')}
 window.closeModal=()=>document.getElementById('modal')?.classList.remove('show');window.LvbanNav=nav;window.LvbanCopy=copy;
 window.LvbanFav=(type,id)=>{LvbanStore.fav(type==='food'?'foods':'spots',id);toast('收藏已更新')};
 function detail(item,type){const food=type==='food';modal(`<div class="section-title"><h2>${esc(item.name)}</h2><button class="mini" onclick="closeModal()">关闭</button></div><div class="detail"><div class="kv"><b>城市</b><br>${esc(item.city)}</div><div class="kv"><b>详细地址</b><br>${esc(item.address)}</div>${item.transport?`<div class="kv"><b>交通</b><br>${esc(item.transport)}</div>`:''}<div class="kv"><b>${food?'人均':'门票'}</b><br>${esc(item.price||'暂无')}</div><div class="kv"><b>${food?'推荐菜':'亮点'}</b><br>${esc(item.dishes||item.highlight||'')}</div><div class="kv"><b>避坑提示</b><br>${esc(item.avoid||'')}</div><div class="actions"><button class="mini primary" onclick='LvbanCopy(${JSON.stringify(item.name)})'>复制名称</button><button class="mini" onclick='LvbanCopy(${JSON.stringify(item.address)})'>复制地址</button><button class="mini" onclick='LvbanNav(${JSON.stringify(item.address)})'>导航</button><button class="mini" onclick='LvbanFav(${JSON.stringify(type)},${JSON.stringify(item.id)})'>${LvbanStore.isFav(food?'foods':'spots',item.id)?'取消收藏':'收藏'}</button></div></div>`)}
 window.LvbanDetail=(type,id)=>{const x=(type==='food'?D.foods:D.spots).find(a=>a.id===id);if(x)detail(x,type)};
 function tabs(el,city,type){el.innerHTML=D.cities.map(c=>`<button class="${c===city?'on':''}" onclick="LvbanCity(${JSON.stringify(type)},${JSON.stringify(c)})">${c}</button>`).join('')}
 window.LvbanCity=(type,c)=>{if(type==='spot')spotCity=c;else foodCity=c;renderCatalog(type)};
 function renderCatalog(type){const food=type==='food',city=food?foodCity:spotCity,tab=document.getElementById(food?'cityFoodTabs':'citySpotTabs'),list=document.getElementById(food?'foodList':'spotList');if(!tab||!list)return;tabs(tab,city,type);const arr=(food?D.foods:D.spots).filter(x=>x.city===city);list.innerHTML=arr.map(x=>`<div class="card glass"><div class="row"><div class="date">${food?'🍜':'📍'}<small>${esc(x.city)}</small></div><div class="item"><h3>${esc(x.name)}</h3><p>${esc(x.address)}</p><p>${esc(food?x.dishes:x.highlight)}</p><div class="actions"><button class="mini primary" onclick='LvbanDetail(${JSON.stringify(type)},${JSON.stringify(x.id)})'>详情</button><button class="mini" onclick='LvbanCopy(${JSON.stringify(x.name)})'>复制名称</button><button class="mini" onclick='LvbanNav(${JSON.stringify(x.address)})'>导航</button><button class="mini" onclick='LvbanFav(${JSON.stringify(type)},${JSON.stringify(x.id)})'>收藏</button></div></div></div></div>`).join('')||'<div class="empty">这个城市暂时没有数据</div>'}
 function tripData(plan){const raw=window.baseTrips?.[plan];if(!raw)return[];const saved=LvbanStore.get().trips.find(x=>x.planKey===plan);return saved?.days?.length?saved.days:raw.map(x=>({date:x[0],title:x[1],summary:x[2],items:[]}))}
 function saveTripDays(plan,days){LvbanStore.patch(s=>{let t=s.trips.find(x=>x.planKey===plan);if(!t){t={id:'builtin-'+plan,planKey:plan,name:plan==='A'?'方案A':'方案B',days:[]};s.trips.push(t)}t.days=days})}
 function renderTrips(plan='A'){activePlan=plan;const c=document.getElementById('tripContent');if(!c)return;const days=tripData(plan);c.innerHTML=`<div class="card glass"><b>${plan==='A'?'福州+平潭+泉州+厦门四城完整版':'福州+平潭+厦门三城休闲版'}</b><p class="sub">${days.length} 天 · 点击 DAY 进入详细管理</p></div>`+days.map((d,i)=>`<div class="card glass"><div class="row"><div class="date">DAY ${i}<small>${esc(d.date)}</small></div><div class="item"><h3>${esc(d.title)}</h3><p>${esc(d.summary)}</p><div class="actions"><button class="mini primary" onclick="LvbanDay(${i})">进入详情</button><button class="mini" onclick="LvbanAddItem(${i})">＋ 添加</button><button class="mini" onclick="LvbanCopyDay(${i})">复制 DAY</button></div></div></div></div>`).join('')}
 window.tripTab=(p,b)=>{document.querySelectorAll('#trips .tabs button').forEach(x=>x.classList.remove('on'));b?.classList.add('on');renderTrips(p)};
 window.LvbanDay=i=>{selectedDay=i;const d=tripData(activePlan)[i],items=d.items||[];modal(`<div class="section-title"><div><h2>DAY ${i}</h2><div class="sub">${esc(d.date)} · ${esc(d.title)}</div></div><button class="mini" onclick="closeModal()">关闭</button></div><div class="detail">${items.length?items.map((x,j)=>`<div class="card glass"><b>${esc(x.time||'待定')} · ${esc(x.name)}</b><p>${esc(x.address||x.note||'')}</p><div class="actions"><button class="mini" onclick="LvbanCopy(${JSON.stringify(x.name)})">复制名称</button><button class="mini" onclick="LvbanNav(${JSON.stringify(x.address||x.name)})">导航</button><button class="mini danger" onclick="LvbanDeleteItem(${j})">删除</button></div></div>`).join(''):'<div class="empty">还没有具体日程，点击“添加”开始完善今天。</div>')}<div class="actions"><button class="mini primary" onclick="LvbanAddItem(${i})">＋ 添加日程</button></div></div>`)};
 window.LvbanAddItem=i=>{closeModal();modal(`<h2>添加到 DAY ${i}</h2><select id="lv-type"><option value="spot">景点</option><option value="food">美食</option><option value="hotel">酒店</option><option value="transport">交通</option><option value="note">备注</option></select><input id="lv-key" placeholder="输入名称"><input id="lv-time" placeholder="时间，例如 09:30"><div class="actions"><button class="mini" onclick="closeModal()">取消</button><button class="mini primary" onclick="LvbanCommitItem(${i})">加入 DAY</button></div>`)};
 window.LvbanCommitItem=i=>{const type=document.getElementById('lv-type').value,key=document.getElementById('lv-key').value.trim(),time=document.getElementById('lv-time').value.trim(),arr=type==='spot'?D.spots:type==='food'?D.foods:[],hit=arr.find(x=>x.name.includes(key))||{name:key||'自定义日程',address:''},days=tripData(activePlan);days[i].items ||= [];days[i].items.push({type,name:hit.name,address:hit.address,time});saveTripDays(activePlan,days);closeModal();renderTrips(activePlan);toast('已加入日程')};
 window.LvbanDeleteItem=j=>{const days=tripData(activePlan);days[selectedDay].items.splice(j,1);saveTripDays(activePlan,days);window.LvbanDay(selectedDay);toast('已删除')};
 window.LvbanCopyDay=i=>{const days=tripData(activePlan),copy=JSON.parse(JSON.stringify(days[i]));copy.title+='（复制）';days.splice(i+1,0,copy);saveTripDays(activePlan,days);renderTrips(activePlan);toast('已复制 DAY')};
 window.openTripEditor=window.openNewTrip=()=>modal(`<h2>新建行程</h2><input id="new-name" placeholder="行程名称"><input id="new-start" type="date"><input id="new-end" type="date"><input id="new-city" placeholder="城市，例如 上海"><input id="new-people" type="number" min="1" placeholder="人数"><input id="new-tags" placeholder="标签"><div class="actions"><button class="mini" onclick="closeModal()">取消</button><button class="mini primary" onclick="LvbanCreateTrip()">创建行程</button></div>`);
 window.LvbanCreateTrip=()=>{const n=document.getElementById('new-name').value.trim(),s=document.getElementById('new-start').value,e=document.getElementById('new-end').value;if(!n||!s||!e)return toast('请填写名称和日期');const a=new Date(s),b=new Date(e),days=[];for(let d=new Date(a);d<=b;d.setDate(d.getDate()+1))days.push({date:d.toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'}),title:'待规划',summary:'点击进入后添加具体日程',items:[]});LvbanStore.patch(x=>x.trips.push({id:'trip-'+Date.now(),planKey:'custom-'+Date.now(),name:n,start:s,end:e,city:document.getElementById('new-city').value,people:document.getElementById('new-people').value,tags:document.getElementById('new-tags').value,days}));closeModal();toast('行程已创建');go('trips')};
 window.clearLocal=()=>{localStorage.removeItem(LvbanStore.key);toast('本地新增数据已清空')};
 function init(){renderCatalog('spot');renderCatalog('food');renderTrips('A')};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
