/* 旅伴旅行管家 · 唯一分享入口 + 好友协作 */
(function(){
  'use strict';
  const API='/api/share';
  const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
  const toast=m=>window.toast?.(m)||alert(m);
  const trip=()=>window.db?.trips?.find(t=>String(t.id)===String(window.activeTrip))||window.db?.trips?.[0]||null;
  const parts=v=>String(v||'').split(/[·,、/|→＞>]+/).map(x=>x.trim()).filter(Boolean);
  const dayCities=d=>{const a=[];parts(d?.city).forEach(c=>{if(!a.includes(c))a.push(c)});(d?.items||[]).forEach(x=>parts(x?.city).forEach(c=>{if(c&&!a.includes(c))a.push(c)}));return a};
  const cities=p=>{const a=[];(p?.days||[]).forEach(d=>dayCities(d).forEach(c=>{if(!a.includes(c))a.push(c)}));return a};
  function style(){if(document.getElementById('lv-share-style'))return;const s=document.createElement('style');s.id='lv-share-style';s.textContent='.lv-share-mask{position:fixed;inset:0;z-index:99999;background:#17172a66;display:flex;align-items:flex-end}.lv-share-sheet{width:100%;max-height:88vh;overflow:auto;background:#f7f8fc;border-radius:28px 28px 0 0;padding:20px;box-sizing:border-box}.lv-share-actions{display:flex;gap:9px;margin-top:14px}.lv-share-actions button{flex:1;padding:13px;border:0;border-radius:14px;background:#efedff;color:#5d4de5;font-weight:800}.lv-share-actions .primary{background:#6958f5;color:#fff}.lv-share-url{width:100%;padding:12px;border:1px solid #e8e6f4;border-radius:14px;background:#fff;box-sizing:border-box}.lv-share-btn{padding:10px 14px;border-radius:13px;background:#6958f5;color:#fff;font-weight:800}';document.head.appendChild(s)}
  async function create(mode){const t=trip();if(!t)throw Error('当前没有可分享的行程');const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode,snapshot:JSON.parse(JSON.stringify(t))})});const d=await r.json();if(!d.ok)throw Error(d.error||'分享失败');return location.origin+location.pathname+'?share='+encodeURIComponent(d.id)}
  function openShare(){style();const o=document.createElement('div');o.className='lv-share-mask';o.innerHTML='<div class="lv-share-sheet"><div style="display:flex;justify-content:space-between;align-items:center"><h2 style="margin:0">分享行程</h2><button class="btn" id="lvSC">关闭</button></div><p class="muted" style="line-height:1.6">只分享当前打开的这个大行程，其他行程不会被带过去。</p><div class="lv-share-actions"><button id="lvSV">只读分享</button><button class="primary" id="lvSE">好友协作编辑</button></div><div id="lvSR" style="display:none;margin-top:14px"><input class="lv-share-url" id="lvSU" readonly><div class="lv-share-actions"><button id="lvSS">系统分享</button><button class="primary" id="lvSX">复制链接</button></div></div></div>';document.body.appendChild(o);o.querySelector('#lvSC').onclick=()=>o.remove();const make=async mode=>{try{const url=await create(mode);o.querySelector('#lvSR').style.display='block';o.querySelector('#lvSU').value=url;o.querySelector('#lvSX').onclick=async()=>{await navigator.clipboard?.writeText(url);o.querySelector('#lvSX').textContent='已复制'};o.querySelector('#lvSS').onclick=()=>navigator.share?navigator.share({title:trip()?.name||'旅伴旅行管家',url}):o.querySelector('#lvSX').click()}catch(e){toast(e.message)}};o.querySelector('#lvSV').onclick=()=>make('view');o.querySelector('#lvSE').onclick=()=>make('edit')}
  window.__lvbanOpenShare=openShare;
  async function loadShared(){const m=location.search.match(/[?&]share=([^&]+)/);if(!m)return;try{const id=decodeURIComponent(m[1]);const r=await fetch(API+'?id='+encodeURIComponent(id));const d=await r.json();if(!d.ok)throw Error(d.error||'分享不存在');const t=d.record.snapshot,p=t.plans?.find(x=>x.id===d.record.activePlan)||t.plans?.[0]||t;const cs=cities(p);let city=cs[0]||'';let di=(p.days||[]).findIndex(x=>dayCities(x).includes(city));if(di<0)di=0;const edit=d.record.mode==='edit';document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));const page=document.getElementById('trips');page.classList.add('active');page.innerHTML='<div class="ut-detail"><div class="ut-head"><div class="ut-title"><h2>'+esc(t.name||'共享行程')+'</h2><p>'+(edit?'好友协作编辑':'只读分享')+' · '+esc(t.start||'')+' → '+esc(t.end||'')+'</p></div></div><div class="ut-row">'+cs.map(c=>'<button class="ut-city '+(c===city?'on':'')+'" data-s="'+esc(c)+'">'+esc(c)+'</button>').join('')+'</div><div id="sharedDays"></div></div>';const render=()=>{const ids=(p.days||[]).map((x,i)=>dayCities(x).includes(city)?i:-1).filter(i=>i>=0);if(!ids.includes(di))di=ids[0]??0;const d0=p.days?.[di];$('#sharedDays').innerHTML='<div class="ut-row">'+ids.map(i=>'<button class="ut-date '+(i===di?'on':'')+'" data-d="'+i+'"><b>'+esc(p.days[i]?.title||'DAY '+(i+1))+'</b><small>'+esc(p.days[i]?.date||'')+'</small></button>').join('')+'</div><div class="ut-label">当天行程详情</div><section class="ut-day"><div class="ut-day-meta"><div class="date">'+esc(d0?.date||'')+'</div><h3>'+esc(d0?.title||'当天行程')+'</h3><p>'+esc(city)+' · '+(d0?.items||[]).length+' 项安排</p></div>'+(d0?.items||[]).map((x,k)=>'<article class="ut-event"><div class="ut-stop">'+esc(x.stopLabel||('第 '+(k+1)+' 站'))+'</div><div class="ut-event-card"><span class="ut-type">'+esc(x.type||'行程')+'</span><h3>'+esc(x.name||'未命名')+'</h3>'+(x.address?'<div class="ut-address">📍 '+esc(x.address)+'</div>':'')+(x.note?'<div class="ut-note">'+esc(x.note)+'</div>':'')+'</div></article>').join('')||'<div class="ut-empty">当天还没有安排</div></section>';$$('[data-d]').forEach(b=>b.onclick=()=>{di=Number(b.dataset.d);render()})};$$('[data-s]').forEach(b=>b.onclick=()=>{city=b.dataset.s;di=0;render()});render()}catch(e){document.body.innerHTML='<div style="padding:40px;text-align:center">'+esc(e.message||'分享链接无效')+'</div>'}}
  if(location.search.includes('share=')){window.addEventListener('load',()=>setTimeout(loadShared,100));return}
  style();
  const boot=document.createElement('script');boot.src='unified-trip-router.js?v=20260821-1';document.head.appendChild(boot);
})();