/* 旅伴旅行管家 · 最终分享层（lvban-travel） */
(function(){
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
  const css=()=>{if(document.getElementById('lv-share-final-style'))return;const s=document.createElement('style');s.id='lv-share-final-style';s.textContent=`
  .lv-share-final-btn{display:inline-flex!important;align-items:center!important;gap:5px!important;padding:9px 13px!important;border-radius:12px!important;background:#6958f5!important;color:#fff!important;font-size:12px!important;font-weight:800!important;box-shadow:0 5px 14px rgba(105,88,245,.18)!important;cursor:pointer!important;position:relative!important;z-index:5!important}
  .lv-share-final-head{display:flex!important;align-items:flex-start!important;justify-content:space-between!important;gap:10px!important}
  .lv-share-final-mask{position:fixed;inset:0;z-index:99999;background:rgba(23,23,42,.5);display:flex;align-items:flex-end}
  .lv-share-final-sheet{width:100%;max-height:88vh;overflow:auto;background:#f7f8fc;border-radius:28px 28px 0 0;padding:20px;box-sizing:border-box}
  .lv-share-final-url{width:100%;padding:12px;border:1px solid #e8e6f4;border-radius:14px;background:#fff;font-size:12px;box-sizing:border-box}
  .lv-share-final-actions{display:flex;gap:8px;margin-top:12px}.lv-share-final-actions button{flex:1;padding:12px;border:0;border-radius:13px;background:#efedff;color:#5d4de5;font-weight:800}.lv-share-final-actions .primary{background:#6958f5;color:#fff}
  .lv-share-readonly{display:inline-block;margin-top:9px;padding:6px 9px;border-radius:10px;background:rgba(255,255,255,.18);font-size:11px}
  `;document.head.appendChild(s)};
  const bytesToB64=u=>{let s='';for(let i=0;i<u.length;i+=0x8000)s+=String.fromCharCode(...u.subarray(i,i+0x8000));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
  const b64ToBytes=s=>{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const x=atob(s),u=new Uint8Array(x.length);for(let i=0;i<x.length;i++)u[i]=x.charCodeAt(i);return u};
  async function encode(o){const raw=new TextEncoder().encode(JSON.stringify(o));if('CompressionStream' in window){try{const cs=new CompressionStream('gzip'),w=cs.writable.getWriter();w.write(raw);w.close();return'g.'+bytesToB64(new Uint8Array(await new Response(cs.readable).arrayBuffer()))}catch(e){}}return'r.'+bytesToB64(raw)}
  async function decode(t){const a=t.split('.'),type=a.shift(),u=b64ToBytes(a.join('.'));if(type==='g'&&'DecompressionStream' in window){const ds=new DecompressionStream('gzip'),w=ds.writable.getWriter();w.write(u);w.close();return JSON.parse(new TextDecoder().decode(await new Response(ds.readable).arrayBuffer()))}return JSON.parse(new TextDecoder().decode(u))}
  function getSnapshot(){const plan=window.state?.plan||'A';const arr=window.schedules?.[plan]||[];return{v:2,readonly:true,name:'十一福建游',plan,days:JSON.parse(JSON.stringify(arr))}}
  async function share(){try{const token=await encode(getSnapshot());const url=location.origin+location.pathname+'#share='+token;const o=document.createElement('div');o.className='lv-share-final-mask';o.innerHTML=`<div class="lv-share-final-sheet"><div style="display:flex;justify-content:space-between;align-items:center"><h2 style="margin:0">分享行程</h2><button class="btn" id="lvShareClose">关闭</button></div><p class="muted" style="line-height:1.6;margin:9px 0 12px">当前分享：十一福建游 · 方案 ${esc(window.state?.plan||'A')}。朋友打开后只读查看这份行程，不会读取你的其他本地数据。</p><input class="lv-share-final-url" readonly value="${esc(url)}"><div class="lv-share-final-actions"><button id="lvShareSystem">系统分享</button><button class="primary" id="lvShareCopy">复制链接</button></div></div>`;document.body.appendChild(o);o.querySelector('#lvShareClose').onclick=()=>o.remove();o.querySelector('#lvShareCopy').onclick=async()=>{try{await navigator.clipboard.writeText(url)}catch(e){const i=o.querySelector('input');i.select();document.execCommand('copy')}o.querySelector('#lvShareCopy').textContent='已复制'};o.querySelector('#lvShareSystem').onclick=async()=>{if(navigator.share)await navigator.share({title:'十一福建游',text:'旅伴旅行管家 · 只读行程',url});else o.querySelector('#lvShareCopy').click()} }catch(e){alert('分享链接生成失败')}}
  function inject(){css();if(location.hash.startsWith('#share='))return;const detail=document.getElementById('tripDetail');if(!detail)return;const head=detail.querySelector('.trip-head');if(!head)return;if(head.querySelector('.lv-share-final-btn'))return;const btn=document.createElement('button');btn.type='button';btn.className='lv-share-final-btn';btn.innerHTML='↗ 分享';btn.onclick=e=>{e.stopPropagation();share()};const wrap=document.createElement('div');wrap.className='lv-share-final-head';while(head.firstChild)wrap.appendChild(head.firstChild);wrap.appendChild(btn);head.appendChild(wrap)}
  function renderShared(s){css();const days=s?.days||[];if(!days.length){document.body.innerHTML='<div class="empty">分享链接无效</div>';return}document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById('trips')?.classList.add('active');const box=document.getElementById('tripDetail');let i=0;const draw=()=>{const d=days[i]||{};box.innerHTML=`<div style="padding:12px 2px 110px"><div style="background:linear-gradient(135deg,#715ff6,#9b7af5 55%,#42bd88);color:#fff;border-radius:24px;padding:20px;margin-bottom:14px"><h2 style="margin:0 0 6px">${esc(s.name||'共享行程')}</h2><div style="font-size:12px;opacity:.9">方案 ${esc(s.plan||'A')} · 只读分享</div><span class="lv-share-readonly">朋友只能查看</span></div><div style="display:flex;gap:8px;overflow:auto;padding:2px 0 12px">${days.map((x,n)=>`<button data-sday="${n}" style="flex:0 0 auto;border:1px solid #e8e6f4;background:${n===i?'#6958f5':'#fff'};color:${n===i?'#fff':'#555'};border-radius:14px;padding:10px 13px"><b>DAY ${n+1}</b><small style="display:block;margin-top:3px">${esc(x.date||'')}</small></button>`).join('')}</div><div class="card"><div class="crumb">${esc(d.date||'')}</div><h2 style="margin:0">${esc(d.title||'当天行程')}</h2></div><div class="timeline">${(d.items||[]).map((x,n)=>`<div class="event card"><div class="event-time">${esc(x[0]||'')}</div><h3>${esc(x[1]||'')}</h3><div class="addr">📍 ${esc(x[2]||'')}</div><div class="muted" style="margin-top:5px">${esc(x[3]||'')}</div></div>`).join('')}</div></div>`;box.querySelectorAll('[data-sday]').forEach(b=>b.onclick=()=>{i=Number(b.dataset.sday);draw()})};draw()}
  async function load(){if(!location.hash.startsWith('#share='))return;try{renderShared(await decode(location.hash.slice(7)))}catch(e){alert('这个分享链接无效或已损坏')}}
  css();setTimeout(inject,50);setTimeout(inject,300);setTimeout(inject,1000);setInterval(inject,500);new MutationObserver(inject).observe(document.body,{childList:true,subtree:true});window.addEventListener('load',()=>setTimeout(load,250));window.addEventListener('hashchange',load);

  /* ===== 我的行程 V2：大行程 → 城市 → 城市日期 → 当天节点 ===== */
  const v2style=document.createElement('style');v2style.textContent=`
  .lv-v2-head{display:flex;align-items:center;gap:10px;margin:4px 0 12px}.lv-v2-back{background:transparent;color:#6958f5;font-weight:800;padding:6px 4px}.lv-v2-title{flex:1;text-align:center}.lv-v2-title h2{margin:0;font-size:21px}.lv-v2-title .sub{margin-top:4px;color:#77788b;font-size:12px}.lv-v2-row{display:flex;gap:8px;overflow:auto;padding:4px 0 10px}.lv-v2-city,.lv-v2-date{flex:0 0 auto;border:1px solid #e8e6f4;background:#fff;border-radius:15px;padding:10px 14px;color:#444;font-weight:700}.lv-v2-city.on,.lv-v2-date.on{background:#6958f5;color:#fff;border-color:#6958f5}.lv-v2-date small{display:block;font-size:10px;margin-top:3px;opacity:.75}.lv-v2-label{margin:10px 0 6px;font-size:12px;color:#77788b;font-weight:800}.lv-v2-event{margin:10px 0;padding:15px 16px;border-radius:21px;background:#fff;border:1px solid #fff;box-shadow:0 10px 28px rgba(64,58,138,.07)}.lv-v2-time{font-size:12px;color:#6958f5;font-weight:900}.lv-v2-event h3{margin:5px 0;font-size:16px}.lv-v2-addr{font-size:12px;color:#77788b;line-height:1.5}.lv-v2-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.lv-v2-actions button{padding:8px 10px;border-radius:11px;background:#efedff;color:#5d4de5;font-size:12px;font-weight:700}.lv-v2-actions .danger{background:#fff0f1;color:#d64d5b}.lv-v2-route{display:inline-block;margin-left:6px;padding:4px 7px;border-radius:8px;background:#f0eeff;color:#5d4de5;font-size:10px}
  `;document.head.appendChild(v2style);
  const dbx=()=>window.db&&typeof window.db==='object'?window.db:null;
  const cities=(t,p)=>{const a=[];const add=x=>{x=String(x||'').trim();if(x&&!a.includes(x))a.push(x)};(p?.days||[]).forEach(d=>add(d.city));(p?.days||[]).forEach(d=>(d.items||[]).forEach(i=>add(i.city)));(Array.isArray(t?.cityDurations)?t.cityDurations:[]).forEach(x=>add(x.city));String(t?.city||'').split(/[·,、/|→]+/).forEach(add);return a};
  const dayCity=(t,p,i)=>{const d=p?.days?.[i];if(d?.city)return d.city;const ic=(d?.items||[]).map(x=>x.city).filter(Boolean);if(ic.length)return ic[0];const cs=cities(t,p);const text=[d?.title||'',...(d?.items||[]).flatMap(x=>[x.name||'',x.address||''])].join(' ');return cs.find(c=>text.includes(c))||''};
  const daysFor=(t,p,c)=> (p?.days||[]).map((d,i)=>({d,i})).filter(x=>dayCity(t,p,x.i)===c);
  window.__lvV2City=window.__lvV2City||null;window.__lvV2Day=window.__lvV2Day||0;
  function renderV2(){const db=dbx();const box=document.getElementById('tripDetail');if(!db?.trips?.length||!box)return;const t=db.trips.find(x=>x.id===window.activeTrip)||db.trips[0];const p=(t.plans||[]).find(x=>x.id===window.activePlan)||(t.plans||[])[0];if(!t||!p)return;const cs=cities(t,p);let city=window.__lvV2City;if(!city||!cs.includes(city))city=cs[0]||'';const ds=daysFor(t,p,city);let di=ds.some(x=>x.i===window.__lvV2Day)?window.__lvV2Day:(ds[0]?.i??0);window.__lvV2City=city;window.__lvV2Day=di;const d=p.days?.[di]||{date:'',title:'当天行程',items:[]};const multi=(t.plans||[]).length>1;box.innerHTML=`<div class="lv-v2-head"><button class="lv-v2-back" onclick="window.__lvV2City=null;window.__lvV2Day=0;location.hash='';renderTrips()">‹ 返回</button><div class="lv-v2-title"><h2>${esc(t.name||'')}</h2><div class="sub">${esc(t.city||cs.join(' · '))}</div></div>${multi?`<span class="lv-v2-route">${esc(p.name||'方案')}</span>`:''}</div><div class="lv-v2-label">城市</div><div class="lv-v2-row">${cs.map(c=>`<button class="lv-v2-city ${c===city?'on':''}" onclick="window.__lvV2City=${JSON.stringify(c)};window.__lvV2Day=0;renderTrips()">${esc(c)}</button>`).join('')}</div><div class="lv-v2-label">${esc(city)} · 日期</div><div class="lv-v2-row">${ds.map(x=>`<button class="lv-v2-date ${x.i===di?'on':''}" onclick="window.__lvV2Day=${x.i};renderTrips()"><b>${esc(x.d.label||('DAY '+(x.i+1)))}</b><small>${esc(x.d.date||'')}</small></button>`).join('')}</div><div class="card" style="margin-top:8px"><div class="crumb">当天行程详情</div><h2 style="margin:0">${esc(d.title||d.label||('DAY '+(di+1)))}</h2><div class="muted" style="margin-top:5px">${esc(d.date||'')} · ${esc(city)}</div></div><div>${(d.items||[]).length?(d.items||[]).map((it,k)=>{const x=Array.isArray(it)?{time:it[0],name:it[1],address:it[2],note:it[3],type:it[4]}:it;return `<article class="lv-v2-event"><div class="lv-v2-time">${esc(x.time||'未定')} <span class="lv-v2-route">${esc(x.type||'日程')}</span></div><h3>${esc(x.name||'未命名日程')}</h3><div class="lv-v2-addr">📍 ${esc(x.address||'暂无地址')}</div>${x.note?`<div class="muted" style="margin-top:5px">${esc(x.note)}</div>`:''}<div class="lv-v2-actions"><button onclick='v2Copy(${JSON.stringify(x.address||'')})'>复制地址</button><button onclick='v2Nav(${JSON.stringify(x.name||'')},${JSON.stringify(x.address||'')})'>导航</button><button onclick="openItemEditor(${k})">编辑</button><button class="danger" onclick="deleteItem(${k})">删除</button></div></article>`}).join(''):'<div class="empty">当天暂无行程</div>'}</div>`}
  window.v2Copy=t=>{navigator.clipboard?.writeText(String(t||''));toast?.('已复制')};window.v2Nav=(n,a)=>window.open('https://www.amap.com/search?query='+encodeURIComponent((n||'')+' '+(a||'')),'_blank','noopener');window.renderTrips=renderV2;
  /* 加入行程：大行程 → 城市 → 该城市已有日期；默认最后一天 */
  window.addCatalog=function(type,id){const db=dbx();const src=type==='food'?db?.foods:db?.spots;const item=src?.find(x=>x.id===id);if(!item)return;window.__lvAdd={type,item};const trips=db.trips||[];modal('加入行程',`<div class="lv-v2-label">第一步 · 选择大行程</div>${trips.map((t,i)=>`<button class="lv-v2-city" style="display:block;width:100%;text-align:left;margin:6px 0" onclick="lvAddTrip(${i})"><b>${esc(t.name||'未命名行程')}</b><small style="display:block;color:#77788b;margin-top:4px">${esc(t.city||'多城市')} · ${esc(t.start||'')} → ${esc(t.end||'')}</small></button>`).join('')}`)};
  window.lvAddTrip=function(i){const db=dbx(),t=db?.trips?.[i];if(!t)return;window.__lvAddTrip=i;const p=(t.plans||[]).find(x=>x.id===window.activePlan)||(t.plans||[])[0];const cs=cities(t,p);document.getElementById('modalBody').innerHTML=`<div class="lv-v2-label">第一步 · 已选择大行程</div><div class="card"><b>${esc(t.name||'')}</b></div><div class="lv-v2-label">第二步 · 选择城市</div><div class="lv-v2-row">${cs.map(c=>`<button class="lv-v2-city" onclick="lvAddCity(${JSON.stringify(c)})">${esc(c)}</button>`).join('')}</div><div id="lvAddDates" class="muted">请选择城市</div>`};
  window.lvAddCity=function(city){const db=dbx(),t=db?.trips?.[window.__lvAddTrip];const p=(t?.plans||[]).find(x=>x.id===window.activePlan)||(t?.plans||[])[0];const ds=daysFor(t,p,city);window.__lvAddCity=city;const dates=document.getElementById('lvAddDates');if(!ds.length){dates.innerHTML='<div class="empty">这个大行程没有该城市的行程日期，不能加入。</div>';return}window.__lvAddDay=ds[ds.length-1].i;dates.innerHTML=`<div class="lv-v2-label">第三步 · 选择日期</div><div class="lv-v2-row">${ds.map(x=>`<button class="lv-v2-date ${x.i===window.__lvAddDay?'on':''}" onclick="window.__lvAddDay=${x.i};lvAddCity(${JSON.stringify(city)})"><b>${esc(x.d.label||('DAY '+(x.i+1)))}</b><small>${esc(x.d.date||'')}</small></button>`).join('')}</div><div class="muted" style="margin:8px 0">默认选择 ${esc(ds[ds.length-1].d.date||'最后一天')}，加入后排在当天最后一个行程节点之后。</div><button class="btn primary" style="width:100%;margin-top:8px" onclick="lvConfirmAdd()">确认加入</button>`};
  window.lvConfirmAdd=function(){const db=dbx(),t=db?.trips?.[window.__lvAddTrip];const p=(t?.plans||[]).find(x=>x.id===window.activePlan)||(t?.plans||[])[0];const d=p?.days?.[window.__lvAddDay];const item=window.__lvAdd?.item;if(!d||!item)return;d.items=d.items||[];d.items.push({id:window.uid?.()||Date.now().toString(),time:'',type:window.__lvAdd.type==='food'?'美食':'景点',name:item.name,address:item.address||'',city:window.__lvAddCity||item.city||'',budget:Number(item.price)||0,note:'从'+(window.__lvAdd.type==='food'?'美食':'景点')+'加入'});window.save?.();window.activeTrip=t.id;window.activePlan=p.id;window.__lvV2City=window.__lvAddCity;window.__lvV2Day=window.__lvAddDay;closeModal();renderTrips();toast?.('已加入该城市最后一个行程节点之后')};
  setTimeout(()=>{if(!location.hash.startsWith('#share=')&&window.db?.trips?.length)renderV2()},80);
})();