/* 旅伴旅行管家 · 行程列表分享入口 */
(function(){
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const trips=()=>Array.isArray(window.db?.trips)?window.db.trips:[];
  const b64=u=>{let s='';for(let i=0;i<u.length;i+=0x8000)s+=String.fromCharCode(...u.subarray(i,i+0x8000));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')};
  async function encode(data){const raw=new TextEncoder().encode(JSON.stringify(data));if('CompressionStream' in window){try{const cs=new CompressionStream('gzip'),w=cs.writable.getWriter();w.write(raw);w.close();const buf=await new Response(cs.readable).arrayBuffer();return 'g.'+b64(new Uint8Array(buf))}catch(e){}}return 'r.'+b64(raw)}
  function toast(msg){if(typeof window.toast==='function'){window.toast(msg);return}alert(msg)}
  async function shareTrip(id){const t=trips().find(x=>x.id===id);if(!t){toast('找不到这个行程');return}const p=t.plans?.find(x=>x.id===window.activePlan)||t.plans?.[0];if(!p){toast('这个行程还没有方案');return}const snapshot={v:1,readonly:true,trip:{id:t.id,name:t.name,city:t.city,start:t.start,end:t.end,people:t.people,cityDurations:t.cityDurations||[],plans:[JSON.parse(JSON.stringify(p))]}};try{const token=await encode(snapshot);const url=location.origin+location.pathname+'#share='+token;show(url,t.name||'当前行程',p.name||'当前方案')}catch(e){toast('分享链接生成失败')}}
  function show(url,name,plan){document.getElementById('lv-share-list-overlay')?.remove();const o=document.createElement('div');o.id='lv-share-list-overlay';o.style='position:fixed;inset:0;z-index:10001;background:rgba(23,23,42,.52);display:flex;align-items:flex-end';o.innerHTML=`<div style="width:100%;max-height:86vh;overflow:auto;background:#f7f8fc;border-radius:28px 28px 0 0;padding:20px;box-shadow:0 -12px 45px rgba(30,25,70,.22)"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><h3 style="margin:0">分享行程</h3><button id="lv-share-list-close" style="border:0;background:#fff;border-radius:12px;padding:9px 13px">关闭</button></div><p style="color:#77788b;font-size:12px;line-height:1.65;margin:10px 0">当前分享：${esc(name)} · ${esc(plan)}。朋友打开后只能查看这份指定行程。</p><input id="lv-share-list-url" readonly value="${esc(url)}" style="width:100%;padding:12px;border:1px solid #e4defd;border-radius:14px;background:#fff;font-size:12px;box-sizing:border-box"><div style="display:flex;gap:8px;margin-top:12px"><button id="lv-share-list-copy" style="flex:1;border:0;border-radius:13px;padding:12px;background:#6958f5;color:#fff;font-weight:800">复制链接</button></div></div>`;document.body.appendChild(o);o.querySelector('#lv-share-list-close').onclick=()=>o.remove();o.querySelector('#lv-share-list-copy').onclick=async()=>{try{await navigator.clipboard.writeText(url);toast('分享链接已复制')}catch(e){const i=o.querySelector('#lv-share-list-url');i.select();document.execCommand('copy');toast('分享链接已复制')}}}
  function inject(){const list=document.getElementById('tripList');if(!list)return;const cards=[...list.querySelectorAll('.trip-card')];const data=trips();cards.forEach((card,i)=>{if(i>=data.length||card.dataset.shareReady)return;card.dataset.shareReady='1';card.style.position='relative';const b=document.createElement('button');b.type='button';b.textContent='分享';b.style='position:absolute;right:10px;top:10px;z-index:5;border:0;border-radius:11px;padding:7px 10px;background:#6958f5;color:#fff;font-weight:800;box-shadow:0 5px 14px rgba(105,88,245,.18)';b.onclick=e=>{e.preventDefault();e.stopPropagation();shareTrip(data[i].id)};card.appendChild(b)});}
  setTimeout(inject,100);setTimeout(inject,500);setTimeout(inject,1200);setInterval(inject,700);new MutationObserver(inject).observe(document.body,{childList:true,subtree:true});
})();
