/* TravelMate stable UI recovery layer
 * This file is intentionally self-contained: one navigation layer, one modal layer,
 * one trip creator, one day editor. It is loaded last and repairs legacy script conflicts.
 */
(()=>{
'use strict';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const uid2=()=> 'lv-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);
window.uid=window.uid||uid2;
const data=()=>window.LVBAN_DATA||{};
const trips=()=>window.db?.trips||[];
const current=()=>trips().find(t=>t.id===window.activeTrip)||trips()[0];
const currentPlan=()=>{const t=current();return t?.plans?.find(p=>p.id===window.activePlan)||t?.plans?.[0]};
const day=()=>currentPlan()?.days?.[window.activeDay||0];
const save=()=>{try{window.save?.()}catch(e){try{window.LvbanStore?.patch(s=>s.trips=window.db.trips)}catch(_){} }};
function toast(m){const t=$('#toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}}
window.toast=toast;
function modal(title,html){const m=$('#modal'),t=$('#modalTitle'),b=$('#modalBody');if(!m||!t||!b)return false;t.textContent=title;b.innerHTML=html;m.classList.add('show');m.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');return true}
function close(){const m=$('#modal');if(!m)return;m.classList.remove('show');m.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
window.closeModal=close;
window.openModal=modal;
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===page));document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('on',b.dataset.page===page));if(page==='home')renderHome();if(page==='trips')renderTrips();if(page==='spots')renderCatalog('spots');if(page==='food')renderCatalog('food');if(page==='hotels')renderHotels();if(page==='traffic')renderTraffic();if(page==='ai'&&window.askAI==null)renderAI()}
window.go=go;
function renderHome(){const c=$('#countdown');if(!c)return;const now=new Date();now.setHours(0,0,0,0);const t=trips().filter(x=>x.start&&new Date(x.start+'T00:00:00')>=now).sort((a,b)=>a.start.localeCompare(b.start))[0];if(!t){c.innerHTML='<div><span>旅行倒计时</span><b>还没有未来行程</b></div>';return}const d=Math.ceil((new Date(t.start+'T00:00:00')-now)/86400000);c.innerHTML='<div><span>最近一次旅行</span><b>'+esc(d===0?'今天':'还有 '+d+' 天')+'</b></div><strong>'+esc(t.name)+'</strong><small>'+esc(t.start)+' · '+esc(t.city||'')+'</small>'}
function renderTrips(){const root=$('#tripList'),detail=$('#tripDetail');if(!root||!detail)return;detail.innerHTML='';root.innerHTML='<div class="trip-head"><div><h2>我的行程</h2><p>管理你的旅行计划</p></div><button class="newTripBtn" onclick="newTrip()">＋ 新建行程</button></div>';const ts=trips();if(!ts.length){root.innerHTML+='<div class="empty"><div class="big">🗓️</div><p>还没有行程，创建一个开始吧</p><button class="newTripBtn" onclick="newTrip()">创建行程</button></div>';return}const g=document.createElement('div');g.className='tripgrid';ts.forEach(t=>{const c=document.createElement('article');c.className='trip-card';c.innerHTML='<button class="more" type="button" aria-label="行程操作">•••</button><div class="trip-cover">'+esc(t.city||'旅行')+'</div><h3>'+esc(t.name||'未命名行程')+'</h3><div class="trip-meta">'+esc(t.start||'')+' → '+esc(t.end||'')+'</div><div class="trip-meta">'+esc(t.city||'未设置目的地')+'</div><button class="openTrip" type="button">查看行程</button>';c.querySelector('.more').onclick=()=>tripMenu(t.id);c.querySelector('.openTrip').onclick=()=>openTrip(t.id);g.appendChild(c)});root.appendChild(g)}
function openTrip(id){window.activeTrip=id;window.activePlan=trips().find(t=>t.id===id)?.plans?.[0]?.id||'A';window.activeDay=0;renderTripDetail()}
window.openTrip=openTrip;window.selectTrip=openTrip;
function renderTripDetail(){const t=current(),root=$('#tripList'),detail=$('#tripDetail');if(!t||!root||!detail)return;root.innerHTML='';const p=currentPlan();const days=p?.days||[];const i=Math.max(0,Math.min(window.activeDay||0,days.length-1));window.activeDay=i;const d=days[i];detail.innerHTML='<div class="detail-top"><div><button class="back" type="button">‹ 返回我的行程</button><h2>'+esc(t.name)+'</h2><p>'+esc(t.city||'')+' · '+esc(t.start||'')+' → '+esc(t.end||'')+'</p></div><button class="more" type="button">•••</button></div>'+(t.plans?.length>1?'<div class="routeTabs">'+t.plans.map(x=>'<button class="route '+(x.id===p.id?'on':'')+'" type="button">'+esc(x.name)+'</button>').join('')+'</div>':'')+'<div class="dateTabs">'+days.map((x,n)=>'<button class="dateTab '+(n===i?'on':'')+'" type="button"><b>'+esc((x.date||'').slice(5))+'</b><small>'+esc(x.title||'待安排')+'</small></button>').join('')+'</div><div class="dayHeader"><div><h3>'+esc(d?.title||'当天行程')+'</h3><p>'+esc(d?.date||'')+'</p></div><div><button class="btn" type="button" id="delDay">删除当天</button><button class="btn" type="button" id="addDay">＋ 添加一天</button></div></div><div class="timeline">'+(d?.items||[]).map(eventHTML).join('')+'</div><button class="addEventBtn" type="button" id="addEvent">＋ 添加日程</button>';
detail.querySelector('.back').onclick=()=>go('trips');detail.querySelector('.more').onclick=()=>tripMenu(t.id);detail.querySelectorAll('.route').forEach((b,n)=>b.onclick=()=>{window.activePlan=p?.id===t.plans[n]?.id?t.plans[n].id:t.plans[n].id;window.activeDay=0;renderTripDetail()});detail.querySelectorAll('.dateTab').forEach((b,n)=>b.onclick=()=>{window.activeDay=n;renderTripDetail()});$('#delDay').onclick=deleteDay;$('#addDay').onclick=addDay;$('#addEvent').onclick=openDayEditor;detail.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openItemEditor(+b.dataset.edit));detail.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteItem(+b.dataset.del));detail.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyAddress(b.dataset.copy));detail.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigateTo(b.dataset.nav))}
window.renderTripDetail=renderTripDetail;
function eventHTML(x,i){return '<div class="event"><div class="eventTime">'+esc(x.time||'')+'</div><div class="eventBody"><h3>'+esc(x.name||'未命名')+'</h3><div class="address">📍 '+esc(x.address||'暂无地址')+'</div>'+(x.note?'<p>'+esc(x.note)+'</p>':'')+'<div class="eventActions"><button type="button" data-edit="'+i+'">编辑</button><button type="button" class="dangerText" data-del="'+i+'">删除</button><button type="button" data-copy="'+esc(x.address||'')+'">复制地址</button><button type="button" data-nav="'+esc(x.address||x.name||'')+'">导航</button></div></div></div>'}
function deleteDay(){const p=currentPlan();if(!p?.days?.length)return;if(!confirm('删除当天及当天所有日程？'))return;p.days.splice(window.activeDay,1);if(!p.days.length)p.days.push({id:uid(),label:'DAY 1',date:current().start,title:'待安排',items:[]});window.activeDay=Math.min(window.activeDay,p.days.length-1);save();renderTripDetail()}
function addDay(){const p=currentPlan(),t=current();if(!p||!t)return;const last=p.days[p.days.length-1],d=new Date((last?.date||t.end)+'T00:00:00');d.setDate(d.getDate()+1);p.days.push({id:uid(),label:'DAY '+p.days.length,date:d.toISOString().slice(0,10),title:'待安排',items:[]});window.activeDay=p.days.length-1;save();renderTripDetail()}
function tripMenu(id){const t=trips().find(x=>x.id===id);if(!t)return;modal('行程操作','<div class="menuList"><button type="button" id="mEdit">编辑行程</button><button type="button" id="mCopy">复制行程</button><button type="button" class="dangerText" id="mDel">删除行程</button></div>');$('#mEdit').onclick=()=>editTrip(id);$('#mCopy').onclick=()=>duplicateTrip(id);$('#mDel').onclick=()=>deleteTrip(id)}
window.tripMenu=tripMenu;
function deleteTrip(id){if(!confirm('确定删除整个行程吗？删除后无法恢复。'))return;window.db.trips=trips().filter(x=>x.id!==id);save();close();window.activeTrip=trips()[0]?.id||null;renderTrips();toast('行程已删除')}
window.deleteTrip=deleteTrip;
function duplicateTrip(id){const t=trips().find(x=>x.id===id);if(!t)return;const c=JSON.parse(JSON.stringify(t));c.id=uid();c.name=(c.name||'行程')+'（副本）';window.db.trips.push(c);save();close();renderTrips();toast('已复制')}
function editTrip(id){const t=trips().find(x=>x.id===id);if(!t)return;modal('编辑行程','<div class="form"><label>行程名称</label><input id="etName" value="'+esc(t.name)+'"><label>目的地</label><input id="etCity" value="'+esc(t.city||'')+'"><button class="btn primary" id="saveTrip">保存</button></div>');$('#saveTrip').onclick=()=>{t.name=$('#etName').value.trim()||t.name;t.city=$('#etCity').value.trim()||t.city;save();close();renderTrips()}}
let chosen=[];let createMode='manual';
function cityList(){const d=data();let a=[];if(Array.isArray(d.cities))a=d.cities.map(x=>typeof x==='string'?x:x?.name).filter(Boolean);if(!a.length){const c=window.CITY_DATA||window.cities||window.LVBAN_CITIES;if(Array.isArray(c))a=c.map(x=>typeof x==='string'?x:x?.name).filter(Boolean);else if(c&&typeof c==='object')a=Object.values(c).flat().map(x=>typeof x==='string'?x:x?.name||x?.city).filter(Boolean)}const fallback=['北京','上海','广州','深圳','杭州','成都','重庆','西安','厦门','福州','平潭','泉州','南京','苏州','武汉','长沙','青岛','大连','三亚','桂林'];return [...new Set((a.length?a:fallback).filter(Boolean))]}
function newTrip(){chosen=[];createMode='manual';modal('新建行程','<div class="form"><label>行程名称</label><input id="ntName" placeholder="例如：国庆厦门慢旅行"><label>目的地</label><button type="button" class="citySelectTrigger" id="cityTrigger">点击选择城市，可多选</button><div id="pickedCities" class="picked"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><div><label>开始日期</label><input id="ntStart" type="date"></div><div><label>结束日期</label><input id="ntEnd" type="date"></div></div><label class="check"><input id="ntAlternate" type="checkbox"> 是否有备选路线（勾选后才生成方案 A / 方案 B）</label><label>你想怎么创建？</label><div class="createModes"><button type="button" class="mode on" id="manualMode">我自己安排</button><button type="button" class="mode" id="aiMode">让 AI 帮我规划</button></div><button type="button" class="btn primary wide" id="createTripBtn">创建行程</button></div>');$('#cityTrigger').onclick=openCityPicker;$('#manualMode').onclick=()=>{createMode='manual';$('#manualMode').classList.add('on');$('#aiMode').classList.remove('on')};$('#aiMode').onclick=()=>{createMode='ai';$('#aiMode').classList.add('on');$('#manualMode').classList.remove('on')};$('#createTripBtn').onclick=createTrip}
window.newTrip=newTrip;
function openCityPicker(){modal('选择城市','<div class="form"><input id="citySearch" placeholder="搜索城市，例如：厦门"><div id="cityOptions" class="cityResults"></div><button type="button" class="btn primary wide" id="cityDone">确认选择</button></div>');const render=()=>{const q=$('#citySearch').value.trim();const arr=cityList().filter(c=>!q||c.includes(q));$('#cityOptions').innerHTML=arr.slice(0,100).map(c=>'<button type="button" class="cityOption '+(chosen.includes(c)?'on':'')+'" data-city="'+esc(c)+'"><span>'+esc(c)+'</span><small>'+(chosen.includes(c)?'已选择':'选择')+'</small></button>').join('')||'<div class="empty">没有找到城市</div>';$('#cityOptions').querySelectorAll('.cityOption').forEach(b=>b.onclick=()=>{const c=b.dataset.city;chosen.includes(c)?chosen=chosen.filter(x=>x!==c):chosen.push(c);render()})};$('#citySearch').oninput=render;$('#cityDone').onclick=()=>{close();$('#cityTrigger').textContent=chosen.length?'已选择：'+chosen.join(' · '):'点击选择城市，可多选';$('#pickedCities').innerHTML=chosen.map(x=>'<span>'+esc(x)+' ×</span>').join('');};render()}
function createTrip(){const name=$('#ntName')?.value.trim(),start=$('#ntStart')?.value,end=$('#ntEnd')?.value,alt=$('#ntAlternate')?.checked;if(!name||!start||!end)return toast('请填写行程名称和日期');if(end<start)return toast('结束日期不能早于开始日期');if(!chosen.length)return toast('请先选择目的地');const days=[];for(let d=new Date(start+'T00:00:00'),last=new Date(end+'T00:00:00');d<=last;d.setDate(d.getDate()+1)){days.push({id:uid(),label:'DAY '+(days.length+1),date:d.toISOString().slice(0,10),title:chosen.length===1?'待安排':chosen[Math.min(days.length,chosen.length-1)]+' · 待安排',city:chosen[Math.min(days.length,chosen.length-1)],items:[]})}const clone=()=>JSON.parse(JSON.stringify(days)).map(x=>({...x,id:uid(),items:[]}));const t={id:uid(),name,city:chosen.join(' · '),cities:[...chosen],start,end,people:1,hasAlternateRoutes:alt,plans:[{id:'A',name:'方案 A',days:clone()}]};if(alt)t.plans.push({id:'B',name:'方案 B',days:clone()});window.db.trips.push(t);window.activeTrip=t.id;window.activePlan='A';window.activeDay=0;save();chosen=[];close();go('trips');renderTripDetail();toast('行程创建成功');if(createMode==='ai')setTimeout(()=>go('ai'),100)}
window.createTrip=createTrip;
function catalog(type){const d=data();let arr=type==='spots'?(d.spots||[]):type==='food'?(d.foods||[]):(d.hotels||[]);if(!Array.isArray(arr))arr=[];const root=$('#'+(type==='food'?'food':type));if(!root)return;root.innerHTML='<div class="title"><h2>'+({spots:'景点',food:'美食',hotels:'酒店'}[type])+'</h2><p>按城市浏览</p></div><div class="catalogSearch"><input id="catSearch" placeholder="搜索城市或名称"><div class="cityFilters">'+[...new Set(arr.map(x=>x.city).filter(Boolean))].slice(0,40).map(c=>'<button type="button" data-city="'+esc(c)+'">'+esc(c)+'</button>').join('')+'</div></div><div class="catalogGrid" id="catGrid"></div>';const render=q=>{q=(q||'').trim();const rows=arr.filter(x=>!q||String(x.city+' '+x.name+' '+x.address).includes(q));$('#catGrid').innerHTML=rows.map(x=>'<article class="catalogCard"><h3>'+esc(x.name||'')+'</h3><p>📍 '+esc(x.address||'暂无地址')+'</p><small>'+esc(x.highlight||x.dishes||x.description||'')+'</small></article>').join('')||'<div class="empty">暂无匹配内容</div>'};$('#catSearch').oninput=e=>render(e.target.value);root.querySelectorAll('[data-city]').forEach(b=>b.onclick=()=>{const q=b.dataset.city;$('#catSearch').value=q;render(q)});render('')}
function renderCatalog(type){catalog(type)}
function renderHotels(){catalog('hotels')}
function renderTraffic(){const r=$('#traffic');if(!r)return;r.innerHTML='<div class="title"><h2>交通</h2><p>城际与本地出行</p></div><div class="panel"><h3>交通助手</h3><p>进入行程后，可在每条日程中使用「导航」；城际交通可直接在日程里记录车次、机场、车站和出发时间。</p></div>'}
function renderAI(){const r=$('#ai');if(!r)return;r.innerHTML='<div class="title"><h2>AI</h2><p>旅行规划与调整</p></div><div class="panel chat"><div class="messages" id="messages"><div class="msg ai">你好，我是旅伴 AI。告诉我目的地、日期和偏好，我可以帮你规划或调整行程。</div></div><div class="composer"><textarea id="aiInput" rows="1" placeholder="输入你的旅行问题…"></textarea><button class="primary" id="aiSend">发送</button></div></div>';$('#aiSend').onclick=()=>{const v=$('#aiInput').value.trim();if(!v)return;$('#messages').insertAdjacentHTML('beforeend','<div class="msg user">'+esc(v)+'</div><div class="msg ai">我已收到你的需求。AI 接口接入后这里会返回实际规划结果。</div>');$('#aiInput').value=''}}
function recommendations(city){const c=String(city||'').trim();const d=data();const all=[...(d.spots||[]),...(d.foods||[])];return all.filter(x=>!c||x.city===c).slice(0,8)}
function openDayEditor(){const t=current(),d=day(),cities=(t?.cities?.length?t.cities:String(t?.city||'').split(/[·,，、/]/).filter(Boolean));const city=cities[0]||'';modal('添加日程','<div class="form"><label>时间</label><input id="diTime" type="time" value="09:00"><label>安排什么？</label><div class="smartTitle">智能推荐 · '+esc(city||'当前目的地')+'</div><div id="smartRec" class="smartRec"></div><input id="diName" placeholder="例如：南普陀寺"><label>地址</label><input id="diAddr" placeholder="可自动识别，也可手动填写"><label>备注</label><textarea id="diNote" placeholder="交通、门票、餐饮等"></textarea><button type="button" class="btn primary wide" id="saveDayItem">加入当天行程</button></div>');const r=recommendations(city);$('#smartRec').innerHTML=r.map(x=>'<button type="button" data-name="'+esc(x.name)+'" data-address="'+esc(x.address||'')+'"><b>'+esc(x.name)+'</b><small>'+esc(x.address||'')+'</small></button>').join('')||'<span class="muted">当前城市暂无推荐</span>';$('#smartRec').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('#diName').value=b.dataset.name;$('#diAddr').value=b.dataset.address;$('#diName').dispatchEvent(new Event('input',{bubbles:true}))});$('#saveDayItem').onclick=saveDayItem}
window.openDayEditor=openDayEditor;
function saveDayItem(){const d=day(),n=$('#diName')?.value.trim();if(!d||!n)return toast('请填写日程名称');d.items=d.items||[];d.items.push({id:uid(),time:$('#diTime').value||'09:00',name:n,address:$('#diAddr').value.trim(),note:$('#diNote').value.trim(),city:d.city||current()?.cities?.[0]||''});d.items.sort((a,b)=>String(a.time).localeCompare(String(b.time)));save();close();renderTripDetail();toast('已加入当天行程')}
window.saveDayItem=saveDayItem;
function openItemEditor(i){const x=day()?.items?.[i];if(!x)return;modal('编辑日程','<div class="form"><label>时间</label><input id="eiTime" type="time" value="'+esc(x.time)+'"><label>名称</label><input id="eiName" value="'+esc(x.name)+'"><label>地址</label><input id="eiAddr" value="'+esc(x.address)+'"><label>备注</label><textarea id="eiNote">'+esc(x.note||'')+'</textarea><button type="button" class="btn primary" id="saveEdit">保存修改</button></div>');$('#saveEdit').onclick=()=>{x.time=$('#eiTime').value;x.name=$('#eiName').value.trim();x.address=$('#eiAddr').value.trim();x.note=$('#eiNote').value.trim();save();close();renderTripDetail()}}
window.openItemEditor=openItemEditor;
function deleteItem(i){const d=day();if(!d?.items?.[i])return;if(confirm('删除这条日程？')){d.items.splice(i,1);save();renderTripDetail();toast('已删除')}}
window.deleteItem=deleteItem;
function copyAddress(x){if(!x)return toast('暂无地址');if(navigator.clipboard)navigator.clipboard.writeText(x).catch(()=>{});toast('已复制地址')}
function navigateTo(x){if(!x)return;window.open('https://uri.amap.com/search?keyword='+encodeURIComponent(x),'_blank')}
window.navigateTo=navigateTo;window.copyText=copyAddress;
function boot(){try{if(!window.db)window.db={trips:[]};if(!window.activeTrip)window.activeTrip=trips()[0]?.id||null;if(!window.activePlan)window.activePlan=current()?.plans?.[0]?.id||'A';if(!document.querySelector('.page.active'))go('home');else{const p=document.querySelector('.page.active').id;if(p==='trips')renderTrips();else if(p==='spots')renderCatalog('spots');else if(p==='food')renderCatalog('food');else if(p==='hotels')renderHotels();else if(p==='traffic')renderTraffic();else if(p==='home')renderHome()}document.addEventListener('click',e=>{if(e.target=== $('#modal'))close()});const closeBtn=$('#modalCloseBtn');if(closeBtn)closeBtn.onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});}catch(e){console.error('stable-ui boot',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
