(function(){
 const KEY='lvban_pro_store_v1'; const DELETED_KEY='lvban_deleted_trips_v1';
 const defaults={trips:[],favorites:{spots:[],foods:[],hotels:[],other:[]},settings:{},aiMemory:[],tools:{}};
 function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'));}catch(e){return JSON.parse(JSON.stringify(defaults));}}
 function deleted(){try{return JSON.parse(localStorage.getItem(DELETED_KEY)||'[]');}catch(e){return []}}
 function saveStore(s){localStorage.setItem(KEY,JSON.stringify(s));return s;}
 window.LvbanStore={key:KEY,load,save:saveStore,get(){return load()},patch(fn){const s=load();fn(s);return saveStore(s)},export(){const blob=new Blob([JSON.stringify(load(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='lvban-backup-'+Date.now()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)},importFile(file,done){const r=new FileReader();r.onload=()=>{try{saveStore(JSON.parse(r.result));done&&done(true)}catch(e){done&&done(false)}};r.readAsText(file)},fav(type,id){return this.patch(s=>{s.favorites[type] ||= [];const a=s.favorites[type],i=a.indexOf(id);i<0?a.push(id):a.splice(i,1)})},isFav(type,id){return load().favorites[type]?.includes(id)}};
 const uid=()=>('lv-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7)); window.uid=uid;
 function dayMap(arr){return (arr||[]).map((d,i)=>({id:uid(),label:'DAY '+i,date:d.date,title:d.title,city:d.city,items:(d.items||[]).map(x=>({id:uid(),time:x[0]||'09:00',name:x[1]||'',address:x[2]||'',city:guessCity(x[2]||'',d.city),type:guessType(x[1]||''),budget:0,note:x[3]||''}))}));}
 function guessCity(a,fallback=''){if(/福州/.test(a))return '福州';if(/平潭/.test(a))return '平潭';if(/泉州|石狮/.test(a))return '泉州';return fallback||'厦门';}
 function guessType(n){return /酒店/.test(n)?'酒店':/D\d+|C\d+|高铁|动车|前往|机场|车站/.test(n)?'交通':/店|餐|美食|粥|面|牛排|肉粽|沙茶|五香|花生汤|麻糍/.test(n)?'美食':'景点';}
 function makeMainTrip(){const schedules=window.schedules||{};return {id:'trip-main',name:'旅伴旅行管家｜十一福建游',city:'福州 · 平潭 · 厦门',start:'2026-09-28',end:'2026-10-04',people:1,plans:[{id:'A',name:'方案 A',days:dayMap(schedules.A||[])},{id:'B',name:'方案 B',days:dayMap(schedules.B||[])}]};}
 const existing=load(),removed=deleted(); let trips=Array.isArray(existing.trips)?existing.trips.filter(t=>!removed.includes(t.id)):[];
 if(!trips.length&&!removed.includes('trip-main'))trips=[makeMainTrip()];
 window.db={trips,spots:(window.LVBAN_DATA?.spots||[]).map(x=>({...x})),foods:(window.LVBAN_DATA?.foods||[]).map(x=>({...x})),hotels:[],favorites:existing.favorites||{spots:[],foods:[],hotels:[],other:[]}};
 window.activeTrip=window.db.trips[0]?.id||null;window.activePlan=window.db.trips[0]?.plans?.[0]?.id||'A';window.activeDay=0;
 window.save=function(){saveStore({...load(),trips:window.db.trips,favorites:window.db.favorites||load().favorites});};
 window.markTripDeleted=function(id){if(!id)return;const a=deleted();if(!a.includes(id))a.push(id);localStorage.setItem(DELETED_KEY,JSON.stringify(a));};
 window.currentTrip=()=>window.db.trips.find(x=>x.id===window.activeTrip)||window.db.trips[0];
 window.currentPlan=()=>{const t=window.currentTrip();return t?.plans?.find(x=>x.id===window.activePlan)||t?.plans?.[0];};
 window.selectTrip=function(id){window.activeTrip=id;const t=window.currentTrip();window.activePlan=t?.plans?.[0]?.id||'A';window.activeDay=0;window.renderTrips?.();};
 window.switchPlan=function(id){window.activePlan=id;window.activeDay=0;window.__lvbanRenderTripDetail?.()||window.renderTripDetail?.();};

 const recommended=['北京','上海','杭州','成都','重庆','南京','西安','广州','深圳','三亚','福州','厦门'];
 const moreCities=['平潭','泉州','青岛','大连','苏州','长沙','武汉','桂林','昆明','大理','丽江','珠海','汕头','香港','澳门'];
 const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
 const tripDays=(a,b)=>{if(!a||!b)return 0;const x=new Date(a+'T00:00:00'),y=new Date(b+'T00:00:00');return y>=x?Math.floor((y-x)/86400000)+1:0};
 let nt={start:'',end:'',cities:[],days:{},picker:false};
 function ensureStyle(){if(document.getElementById('lv-newtrip-direct-style'))return;const s=document.createElement('style');s.id='lv-newtrip-direct-style';s.textContent='.lvnt{display:grid;gap:10px}.lvnt label{font-size:12px;color:#77788b}.lvnt input{width:100%;padding:12px;border:1px solid #e8e6f4;border-radius:14px;background:#fff;box-sizing:border-box}.lvnt-date{display:grid;grid-template-columns:1fr 1fr;gap:8px}.lvnt-datebox{padding:10px;border:1px solid #e8e6f4;border-radius:16px;background:#fff}.lvnt-datebox b{display:block;font-size:11px;color:#77788b;margin-bottom:4px}.lvnt-citybox{border:1px solid #e8e6f4;border-radius:16px;background:#fff;padding:11px}.lvnt-cityhead{display:flex;justify-content:space-between;align-items:center;cursor:pointer}.lvnt-selected{display:flex;flex-wrap:wrap;gap:6px;margin-top:8px}.lvnt-chip{padding:6px 9px;border-radius:10px;background:#efedff;color:#5d4de5;font-size:11px}.lvnt-picker{display:none;margin-top:10px;padding-top:10px;border-top:1px solid #eee}.lvnt-picker.open{display:block}.lvnt-section{font-size:11px;color:#77788b;margin:6px 0}.lvnt-grid{display:flex;flex-wrap:wrap;gap:7px}.lvnt-city{padding:9px 12px;border:1px solid #e8e6f4;border-radius:12px;background:#fff;color:#444}.lvnt-city.on{background:#6958f5;color:#fff}.lvnt-days{display:grid;gap:8px}.lvnt-row{display:grid;grid-template-columns:1fr 34px 52px 34px;align-items:center;gap:7px;padding:9px 11px;border:1px solid #e8e6f4;border-radius:14px;background:#fff}.lvnt-step{width:34px;height:34px;border-radius:10px;background:#efedff;color:#5d4de5;font-weight:900}.lvnt-count{text-align:center;font-weight:800}.lvnt-total{padding:10px 12px;border-radius:13px;background:#efedff;color:#5d4de5;font-size:12px;font-weight:800}.lvnt-error{font-size:11px;color:#d64d5b}.lvnt-hidden{display:none!important}';document.head.appendChild(s)}
 function distribute(){const total=tripDays(nt.start,nt.end);if(!total||!nt.cities.length)return;let left=total;nt.cities.forEach((c,i)=>{const remain=nt.cities.length-i;nt.days[c]=i===nt.cities.length-1?left:Math.max(1,Math.floor(left/remain));left-=nt.days[c]})}
 function renderCityPicker(){const sel=document.getElementById('lvntSelected'),rec=document.getElementById('lvntRec'),more=document.getElementById('lvntMore');if(!sel)return;sel.innerHTML=nt.cities.length?nt.cities.map(c=>`<span class="lvnt-chip">${esc(c)}</span>`).join(''):'<span style="color:#77788b;font-size:11px">点击选择城市</span>';const paint=(el,list)=>{el.innerHTML=list.map(c=>`<button type="button" class="lvnt-city ${nt.cities.includes(c)?'on':''}" data-city="${esc(c)}">${esc(c)}</button>`).join('');el.querySelectorAll('[data-city]').forEach(b=>b.onclick=e=>{e.stopPropagation();const c=b.dataset.city;if(nt.cities.includes(c))nt.cities=nt.cities.filter(x=>x!==c);else nt.cities.push(c);distribute();renderCityPicker();renderCityDays()})};paint(rec,recommended);paint(more,moreCities)}
 function renderCityDays(){const wrap=document.getElementById('lvntDaysWrap'),box=document.getElementById('lvntDays');if(!wrap||!box)return;if(!nt.cities.length){wrap.classList.add('lvnt-hidden');return}wrap.classList.remove('lvnt-hidden');const total=tripDays(nt.start,nt.end);if(!total){box.innerHTML='<div style="color:#77788b;font-size:11px">先选择完整的开始和结束日期。</div>';return}if(total<nt.cities.length){box.innerHTML=`<div class="lvnt-error">旅行只有 ${total} 天，不能选择 ${nt.cities.length} 个城市。</div>`;return}const sum=nt.cities.reduce((n,c)=>n+Number(nt.days[c]||0),0);box.innerHTML=nt.cities.map(c=>{const v=Number(nt.days[c]||1);return `<div class="lvnt-row"><b>${esc(c)}</b><button type="button" class="lvnt-step" data-city="${esc(c)}" data-op="minus">−</button><span class="lvnt-count">${v}天</span><button type="button" class="lvnt-step" data-city="${esc(c)}" data-op="plus">＋</button></div>`}).join('')+`<div class="lvnt-total">已分配 ${sum} / ${total} 天</div>`+(sum===total?'<div style="font-size:11px;color:#77788b">天数已分配完成，可以创建。</div>':`<div class="lvnt-error">还差 ${Math.abs(total-sum)} 天，请调整。</div>`);box.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>{const c=b.dataset.city,cur=Number(nt.days[c]||1),other=nt.cities.filter(x=>x!==c).reduce((n,x)=>n+Number(nt.days[x]||0),0);if(b.dataset.op==='minus'&&cur>1)nt.days[c]=cur-1;if(b.dataset.op==='plus'&&other+cur<total)nt.days[c]=cur+1;renderCityDays()})}
 function openNewTripDirect(){ensureStyle();nt={start:'',end:'',cities:[],days:{},picker:false};const html=`<div class="lvnt"><div class="trip-level">一级类目：我的行程</div><label>行程名称</label><input id="lvntName" placeholder="例如：成都重庆游"><label>出行日期</label><div class="lvnt-date"><div class="lvnt-datebox"><b>开始日期</b><input id="lvntStart" type="date"></div><div class="lvnt-datebox"><b>结束日期</b><input id="lvntEnd" type="date"></div></div><div id="lvntHint" style="font-size:11px;color:#77788b">先选择开始日期，选完会自动进入结束日期。</div><label>选择城市</label><div class="lvnt-citybox"><div id="lvntCityHead" class="lvnt-cityhead"><b>选择城市</b><span>⌄</span></div><div id="lvntSelected" class="lvnt-selected"></div><div id="lvntPicker" class="lvnt-picker"><div class="lvnt-section">推荐城市</div><div id="lvntRec" class="lvnt-grid"></div><div class="lvnt-section">更多城市</div><div id="lvntMore" class="lvnt-grid"></div></div></div><div id="lvntDaysWrap" class="lvnt-hidden"><label>城市停留天数</label><div id="lvntDays" class="lvnt-days"></div></div><button type="button" class="btn primary" id="lvntCreate">创建行程</button></div>`;if(typeof window.modal!=='function'){alert('新建行程组件未加载');return}window.modal('新建行程',html);const st=document.getElementById('lvntStart'),en=document.getElementById('lvntEnd');st.onchange=()=>{nt.start=st.value;nt.end='';en.value='';en.min=nt.start;document.getElementById('lvntHint').textContent='已选择开始日期，请选择结束日期。';renderCityDays();try{en.focus();en.showPicker?.()}catch(e){}};en.onchange=()=>{nt.end=en.value;document.getElementById('lvntHint').textContent='行程共 '+tripDays(nt.start,nt.end)+' 天';distribute();renderCityDays()};document.getElementById('lvntCityHead').onclick=()=>{nt.picker=!nt.picker;document.getElementById('lvntPicker').classList.toggle('open',nt.picker)};document.getElementById('lvntCreate').onclick=createNewTripDirect;renderCityPicker();renderCityDays()}
 function createNewTripDirect(){const name=document.getElementById('lvntName')?.value.trim(),total=tripDays(nt.start,nt.end),sum=nt.cities.reduce((n,c)=>n+Number(nt.days[c]||0),0);if(!name)return alert('请先填写行程名称');if(!nt.start||!nt.end)return alert('请选择开始和结束日期');if(!nt.cities.length)return alert('请选择至少一个城市');if(total!==sum)return alert('城市天数必须刚好等于旅行总天数');let cur=new Date(nt.start+'T00:00:00'),days=[],ranges=[];nt.cities.forEach(c=>{const n=Number(nt.days[c]);const begin=cur.toISOString().slice(0,10);for(let i=0;i<n;i++){const d=cur.toISOString().slice(0,10);days.push({id:uid(),label:'DAY '+(days.length+1),date:d,title:'待安排',city:c,items:[]});cur.setDate(cur.getDate()+1)}ranges.push({city:c,days:n,start:begin,end:new Date(cur.getTime()-86400000).toISOString().slice(0,10)})});const t={id:uid(),name,start:nt.start,end:nt.end,city:nt.cities.join(' · '),cities:nt.cities.slice(),cityDays:{...nt.days},cityRanges:ranges,people:1,plans:[{id:'A',name:'方案 A',days}]};window.db.trips=Array.isArray(window.db.trips)?window.db.trips:[];window.db.trips.push(t);window.activeTrip=t.id;window.activePlan='A';window.activeDay=0;window._utCity=nt.cities[0];window._utDay=0;window.save?.();window.closeModal?.();window.go?.('trips');setTimeout(()=>{window.openTripCanvas?.(t.id)||window.__lvbanOpenTripDetail?.(t.id);window.renderTrips?.()},0);alert('行程已创建')}
 window.newTrip=openNewTripDirect;window.openNewTrip=openNewTripDirect;window.__lvbanNewTripV2=true;
})();